### ISSUE TITLE
Debug logging helpers?

### ISSUE THREAD

**Issue by zx2c4** [theonemcdonald/pfSense-pkg-WireGuard#100]
I heard that you're interested in providing some debug logs to users, and you're primarily doing this based on the results of the userspace commands you run. That's helpful for systems things, but not so much for network things. Fortunately, there's a nice way you can get debug logs for networking things: `ifconfig wg0 debug`. Once you do this, dmesg will spit out messages prefixed with "wireguard: ", which you should be able to collect. You can turn it back off with `ifconfig wg0 -debug`.

**Comment by theonemcdonald** [comment]
Thanks for the tip, I will look into this!
