### ISSUE TITLE
Wireguard Service not restarted after upgrade

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#102]
Wireguard is not automatically restarting after upgrade.

- pfSense 2.5.1 with Wireguard v0.1.2 loaded via Package Manager
- Wireguard running with several tunnels active.
- Upgraded to v0.1.2_1 (no issues identified as part of upgrade), but the Wireguard Service was not restarted and had to be started manually.

Like other service in pfSense shouldn't the service be restart since I had it running prior to the upgrade?

**Comment by theonemcdonald** [comment]
This is expected when upgrading from the command line. When upgrading from the GUI, pfSense will automatically restart services.

**Comment by Tigger2014** [comment]
How did you upgrade to  v0.1.2_1  was this via CLI or using the repo provided by us in the GUI?

**Comment by gshaffer1** [comment]
> How did you upgrade to v0.1.2_1 was this via CLI or using the repo provided by us in the GUI?

I upgraded using the repo provided by you in the Package Manager GUI.

**Comment by theonemcdonald** [comment]
@Tigger2014 @vajonam Is there anything preventing packages installed from a third-party repo from having their daemons restarted automatically?

**Comment by gshaffer1** [comment]
> @Tigger2014 @vajonam Is there anything preventing packages installed from a third-party repo from having their daemons restarted automatically?

Not that I'm aware of. Everything else looks fine. What would I look for in the logs?

**Comment by theonemcdonald** [comment]
if you "reinstalled" the package through the GUI, does it come up restarted?

**Comment by gshaffer1** [comment]
> if you "reinstalled" the package through the GUI, does it come up restarted?

No. In the services panel on the dashboard it shows the "Start Service" button vice the "Restart Service" and "Stop Service" combo.

**Comment by tigattack** [comment]
I can also reproduce this if that's any help at all 🙂

**Comment by theonemcdonald** [comment]
Restarting services is completely up to the package manager to kick-off the requisite RC script. @tigattack  are you using the official Netgate repository or the unofficial repository? Updates with Netgate are going to start moving much quicker which will largely supplant the usefulness of the unofficial repo.

**Comment by tigattack** [comment]
Unofficial (`http://packages.mced.tech/packages/freebsd_12-2_amd64-ng_ports_251`).

**Comment by theonemcdonald** [comment]
I thought so. @vajonam or @Tigger2014 will need to address this. At this point, I'm only focused on delivering to the mainline Netgate repository. (hint: the latest v0.1.3 code should be merged in very soon officially).
