### ISSUE TITLE
[QUESTION] Considerations Before Upgrading to 21.05/2.5.2

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#103]
Before upgrading to 21.05/2.5.2 is there anything special that needs to be done with the Wireguard Setup.

Do I need to remove the repo before the install?
Will the "experimental" package show up automatically in the main repo or do I need to set a flag somewhere or edit a file?
Do I need to remove the Wireguard Package before hand?

**Comment by vajonam** [comment]
@gshaffer1 the repo will continue to work, with the latest dev releases. however removing the repo will only show the versions that have been pushed to the netgate official repo. (we do this periodically, and  it takes a few few reviews before stuff gets in there)

You will see two packages if you leave the repo installed. 

![image](https://user-images.githubusercontent.com/152501/121039628-40fc9080-c77f-11eb-9f89-ae2ce1f87d4b.png)

and you can pick the right ones.

However just from a best practice and the fact the we haven't tested upgrades with repo enabled. I would do the following

- backup / save wg configs 
- remove repo
- upgrade to 2.5.2 or 21.05
- re-add  repo
