### ISSUE TITLE
[BUG] Package shows up twice

### ISSUE THREAD

**Issue by andrewluebke** [theonemcdonald/pfSense-pkg-WireGuard#104]
**Describe the bug**
The package shows up in the installed package list twice.

**To Reproduce**
I ran the script to allow the current repository to be used by available packages and then installed 0.1.2_1.  I removed one of the installed packages and they both were removed.  Reinstalled the package and two copies appeared.  Looking in the configuration XML there is only one copy of the package referenced.

**Expected behavior**
That the package will only appear once in the installed package list.

**Screenshots**
![System_ Package Manager_ Installed Packages — Mozilla Fi](https://user-images.githubusercontent.com/45699172/120876034-67de7b00-c563-11eb-9432-ab7d4aa52784.png)

**Version information (please complete the following information):**
 - PfSense: 2.6.0.a.20210604.0100
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.2_1

**Comment by theonemcdonald** [comment]
@vajonam @Tigger2014

**Comment by theonemcdonald** [comment]
I'm seeing the same, there is something funky going on with the repo.

**Comment by vajonam** [comment]
@theonemcdonald  this is going to be an issue unless we change our package name to WireGuad-devel. Since the package is available in both repos the current "Installed Packages" code doesn't expect that. so I think the answer is our repo we have to rename our package to -devel or something like that, otherwise.

**Comment by vajonam** [comment]
@andrewluebke  in the meanwhile while we sort this out. I would use the command line to add/upgrade the packages not sure which repo its going to be installed from. I had to specify the full version like `pkg install pfSense-pkg-WireGuard-0.1.2_1` to get it to choose the right one.

**Comment by vajonam** [comment]
The available packages shows.

![image](https://user-images.githubusercontent.com/152501/120893299-9189b780-c5e0-11eb-8fa9-ce29e095c454.png)

But installed shows them as duplicates.

**Comment by vajonam** [comment]
@andrewluebke  This should be fixed now. 

please remove the repo using the script and re-add it using the same script. This will not affect your installed packages, should fix up the duplicate packages showing up.

**Comment by andrewluebke** [comment]
@vajonam That fixed it!  Thanks very much.
