### ISSUE TITLE
Certain private keys being mangled by wg(8)

### ISSUE THREAD

**Issue by completion** [theonemcdonald/pfSense-pkg-WireGuard#105]
I am attempting to setup wireguard (package version 0.1.1 installed using the webUI) on my netgate sg-3100. However I can not seem to get it to connect at all.

My VPN provider is mullvad and this is the config I got from them:
```
[Interface]
PrivateKey = Lm0BA4...
Address = 10.67.82.102/32,fc00:bbbb:bbbb:bb01::4:5265/128
DNS = 193.138.218.74

[Peer]
PublicKey = T1fKJp8knv4kqsfy9O04OIy+1nl5b9ypcnIzdmcfyzM=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 198.54.131.82:51820
```
tunnel settings:
![2021-06-05_03-05](https://user-images.githubusercontent.com/11341916/120890050-fef11480-c5ef-11eb-8963-9d3a9f2dcdab.png)

peer settings:
![2021-06-05_03-06](https://user-images.githubusercontent.com/11341916/120889762-2f37b380-c5ee-11eb-94a6-c599af73d90a.png)

status:
![2021-06-05_03-07](https://user-images.githubusercontent.com/11341916/120889783-45457400-c5ee-11eb-87da-ea839ca69266.png)

`wg showconf tun_wg0`
![2021-06-05_03-10](https://user-images.githubusercontent.com/11341916/120889888-df0d2100-c5ee-11eb-9d37-4b524afe327c.png)

I believe I have set everything up correctly but as shown on the status page no data is being transferred. The only problem I can find is when I run `wg showconf tun_wg0`, the private key differs from the one I entered in the web UI. Is this by design or is something wrong?

Thank you.

**Comment by vajonam** [comment]
That is wired. even when you restart the service it still shows a different private key? Also I noticed when testing mullvad, that it provides you config even if you have paid for it, but never connects. so assuming you have paid for sub with mullvad.

**Comment by completion** [comment]
Yes, the different private key stays through restarts. I even tried changing it with `wg set` but it didn't do anything.

Yes, I have a paid subscription. I am currently using mullvad on other devices and I actually had it working with netgate's wireguard implementation before they removed it.

**Comment by vajonam** [comment]
Did you install from scratch or get here via upgrades? also if you can post the wireguard section from the configl.xml (obfuscated) might shed some light as well.

**Comment by completion** [comment]
Through upgrades of both pfSense and the wireguard package.
```
<wireguard>
	<config>
		<keep_conf>yes</keep_conf>
		<hide_secrets></hide_secrets>
	</config>
	<tunnels>
		<item>
			<addresses></addresses>
			<name>tun_wg0</name>
			<enabled>yes</enabled>
			<descr><![CDATA[Mullvad SEA]]></descr>
			<listenport>51820</listenport>
			<privatekey>Lm0BA4...=</privatekey>
			<publickey>SHRPJKc1SLByfYd3r1mwlUnPGe3ziNTXNJt3XgDMHB8=</publickey>
			<mtu>1500</mtu>
		</item>
	</tunnels>
	<peers>
		<item>
			<allowedips>
				<row>
					<address>0.0.0.0</address>
					<mask>0</mask>
					<descr></descr>
				</row>
				<row>
					<address>::0</address>
					<mask>0</mask>
					<descr></descr>
				</row>
			</allowedips>
			<enabled>yes</enabled>
			<tun>tun_wg0</tun>
			<descr><![CDATA[us177]]></descr>
			<endpoint>198.54.131.82</endpoint>
			<port>51820</port>
			<persistentkeepalive></persistentkeepalive>
			<publickey>T1fKJp8knv4kqsfy9O04OIy+1nl5b9ypcnIzdmcfyzM=</publickey>
			<presharedkey></presharedkey>
		</item>
	</peers>
</wireguard>
```

**Comment by vajonam** [comment]
That looks good. now sure why/how the `showconf` is mismatching from the <config>. 

what does `/usr/local/etc/wireguard/tun_wg0.conf` contain? the correct keys or incorrect ones? you can try moving that file out,  that and restarting the service that should recreate that.

**Comment by completion** [comment]
`/usr/local/etc/wireguard/tun_wg0.conf`:
```
# This WireGuard config file has been created automatically. Do not edit!
# Description: Mullvad SEA

[Interface]
PrivateKey = Lm0BA4...
ListenPort = 51820

# Peer: us177
[Peer]
PublicKey = T1fKJp8knv4kqsfy9O04OIy+1nl5b9ypcnIzdmcfyzM=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 198.54.131.82:51820
```

Correct keys.

**Comment by theonemcdonald** [comment]
AllowedIPs = 0.0.0.0/0,::0/0

v6 should be ::/0

**Comment by completion** [comment]
> AllowedIPs = 0.0.0.0/0,::0/0
> v6 should be ::/0

Huh, I don't know where that extra 0 came from. Like with the private key, it differs based on where you look.
***
I decided to try do a factory reset and then install v0.1.2_1. It did not go very well...

I installed v0.1.2_1 from github which caused the wireguard service not be able to start. `service wireguardd start` says 'Unable to build WireGuard tunnels(s)'. The only way I could get it to start was to delete all tunnels/peers. Then it works fine but if I even create a tunnel with just my privatekey, this makes the service unable to start.

So I uninstalled that version. I went to pfSense's package manager to reinstall v0.1.1 but pfSense only gave me v0.0.8. This happened before right after I upgraded pfSense but I don't know how I got it to give me v0.1.1 before and I was unable to repeat it. I think I ran `pkg update` and then rebooted or something like that but it didn't do the trick this time.

So I installed v0.1.1 from github and #71 is happening again even though when I had v0.1.1 installed before it was able to load the kernel module. On wireguard's status page it says I have v0.1.1_1 installed verses v0.1.1 from before. Maybe thats because this time I installed it using the pkg command and not the web UI?

***
> Correction: I'm having issues with Mullvad too. My other tunnels work fine

Should I contact mullvad's support?

**Comment by Tigger2014** [comment]
@completion please can you join us on discord and we can discuss this much faster. This sounds like it might need some more quick debugging from us.
https://discord.gg/d8vCftC

**Comment by Tigger2014** [comment]
discussed on Discord in Channel  DEBUG105

Private key `Lm0BA4UyPilHH5qnXCfr6Lw8ynecOPor88tljLy3ALk=` is accepted by the web gui but then gets mangled during save and translated into `KG0BA4UyPilHH5qnXCfr6Lw8ynecOPor88tljLy3AHk=` on wg showconf

**Comment by completion** [comment]
Here is another example.
`zQwldrChCYP3P2fZeTtHmj3c/88hxM+TaLIq1mJ28ZY=` turns into 
 `yAwldrChCYP3P2fZeTtHmj3c/88hxM+TaLIq1mJ28VY=`. There seems to be a pattern. Only a few bits are changed.

**Comment by theonemcdonald** [comment]
This seems to be an issue with WireGuard Tools and not with the package itself. I'm going to reach out to Jason and see what he thinks. But the key is correct up until it is passed to wg(8).

**Comment by theonemcdonald** [comment]
After consulting with Jason, this is expected. Mullvad isn't properly clamping those private keys. This shouldn't impact connectivity though. I've built some checks for cases like this and can use these to inform users when an unclamped private key or psk was entered.

**Comment by theonemcdonald** [comment]
I've left some notes in the automatically generated .conf files for those users who happen to be technically motivated to go digging around on disk. This should be sufficient in nudging them that this is expected behavior. Other than that, this scenario will be transparent to end-users via the UI.

![image](https://user-images.githubusercontent.com/3102039/121384798-94edad80-c916-11eb-853f-b5337b61d57d.png)
