### ISSUE TITLE
[BUG] WireGuard Package not present after upgrade to 21.05

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#107]
Previously running 21.02.2 on SG-3100 with Wireguard v0.1.2 Installed via Package Manager GUI.

Before upgrading, removed repo using the command from the wiki page. Did not remove WireGuard.
Upgraded to 21.05.
After upgrade completed, went to Package Manager GUI to upgrade WireGuard to v0.1.2_1. The WireGuard was not present either under the Installed Packages or the Available Packages.

Wireguard is still present and running on the system.

**Comment by vajonam** [comment]
See #103 

pkg remove pfSense-pkg-WireGuard, remove-repo, re-add repo, install package.

**Comment by vajonam** [comment]
I don't have SG-3100. But nothing has changed with the builds. the way the pfSense gui works, that it won't show packages that are installed. when you do an upgrade the it remove ths patch the we do to show unofficial packages to the "Installed Packages" GUI. so remove/re-add repo should sort that out.

**Comment by vajonam** [comment]
@gshaffer1  This is bit of a limitation of the pfSense package manager UI, its not really setup for a package occurring in multiple repos. for now the above work around w/ work.

**Comment by vajonam** [comment]
@gshaffer1 I have updated the scripts.

- remove package
- remove repo
- install new repo
- install package should install new package if not run `pkg install -r mced pfSense-pkg-WireGuard`
- GUI should now keep that package updated. 

Again we are learning how best to do this since the pfSense gui doesn't support multiple repos, short of patching the whole UI this is bit harder.

**Comment by tcquade** [comment]
How do I go about the following (command line or other explicit please!)

remove package
remove repo
install new repo

Ted Quade

**Comment by vajonam** [comment]
@tcquade you can look here. https://github.com/theonemcdonald/pfSense-pkg-WireGuard/wiki/Installation but if you are not comfortable with running those commands or recovering when something goes wrong, please wait for the latest packages to make its way into the netgate repos or for 2.5.2 to be released.

**Comment by tcquade** [comment]
Thanks!

 

That is exactly what I wanted.

 

Ted
