### ISSUE TITLE
Status - Show friendly name of connected Users

### ISSUE THREAD

**Issue by WalkerEdison** [theonemcdonald/pfSense-pkg-WireGuard#109]
Currently the Status page only shows the connected public key of client systems. This can be a pain to track down when you have hundreds of them in there. 

example of current behavior:
![image](https://user-images.githubusercontent.com/59256033/121020318-7ee8bd00-c75d-11eb-9701-2336a288ed1c.png)

It would be much easier if it would show the friendly name to the left,(which we as end users would be able to customize to what we wanted from the time of end point creation.) That way we can tell quickly which end user is compromised rather than having to keep a list outside of pfsense of who has what.

**Comment by vajonam** [comment]
This is fixed in the latest versions where we show the friendly name.

**Comment by vajonam** [comment]
![image](https://user-images.githubusercontent.com/152501/121032497-5373cb80-c779-11eb-925d-3a297615e27a.png)

Thats what the new status table looks like this in 0.1.1 and 0.1.2_1 if your are sideloading.

**Comment by WalkerEdison** [comment]
sweet thank you!
