### ISSUE TITLE
FQDN resolution race at reboot causes peer to not connect

### ISSUE THREAD

**Issue by infosecmatters2021** [theonemcdonald/pfSense-pkg-WireGuard#112]
Assumption: A properly configured WireGuard tunnel should be connected/brought up automatically upon reboot.
Currently, WireGuard status after reboot is: No peers have been configured

Steps to recreate:

1. Working WireGuard configuration and connection is up.
2. Reboot pfSense. 
3. VPN -> WireGuard -> Status (tab) -> Show Peers (button)
Output: No peers have been configured

4. Click Peers (tab)
5. Click pencil icon (Edit)
6. Delete Endpoint Port (51820 (default) appeared in this line)  <-- make a setting change, save it and apply changes to resolve the issue
7. Click Save Peer (button)
8. Click Apply Changes (button)
9. Click Status (tab)
10. Click Show Peers (button)
11. Peer connection shows established.

**Comment by infosecmatters2021** [comment]
Running latest version of code:

2.6.0-DEVELOPMENT (amd64)
built on Wed Jun 09 01:03:58 EDT 2021
FreeBSD 12.2-STABLE

Name | Version | Comment
pfSense-pkg-WireGuard | 0.1.2_6 | pfSense package WireGuard (EXPERIMENTAL)
wireguard-kmod | 0.0.20210606 | WireGuard implementation for the FreeBSD kernel
wireguard-tools-lite | 1.0.20210424 | Fast, modern and secure VPN Tunnel (lite flavor)

**Comment by mrdziobaty** [comment]
Can confirm the same behavior on 2.5.1. After reboot WireGuard -> Status: No peers have been configured.

**Comment by theonemcdonald** [comment]
Interesting, I’m not seeing that on my end. All my peers come up properly on reboot.

so just to confirm, under status you see tunnel entries but # peers is 0?

**Comment by theonemcdonald** [comment]
Also, can you immediately download the tunnel configuration after startup using the new download feature, and redact it? I’m curious what that looks like on startup

**Comment by infosecmatters2021** [comment]
I clicked the download icon and opened the file in textedit (Mac). I redacted parts of the private and public keys (...). 

# This WireGuard config file has been created automatically. Do not edit!

# Description: Description
[Interface]
PrivateKey = yP8...
ListenPort = 51820

# Peer: Description
[Peer]
PublicKey = 0/x2PdBGfc...
AllowedIPs = 0.0.0.0/0
Endpoint = us8500.nordvpn.com:51820
PersistentKeepalive = 25

**Comment by infosecmatters2021** [comment]
![Screenshot 2021-06-11 at 08 49 49](https://user-images.githubusercontent.com/85263005/121714274-87f5c900-ca92-11eb-84a0-11bf30fd6a20.png)
![Screenshot 2021-06-11 at 08 50 06](https://user-images.githubusercontent.com/85263005/121714278-888e5f80-ca92-11eb-8e39-919ab24b382b.png)
![Screenshot 2021-06-11 at 08 49 57](https://user-images.githubusercontent.com/85263005/121714279-8926f600-ca92-11eb-97d4-0cb5fb8bb372.png)

**Comment by infosecmatters2021** [comment]
Followed these steps (redacted a key in screen capture):

Click Peers (tab)
Click pencil icon (Edit)
Delete Endpoint Port (51820 (default) appeared in this line) <-- make a setting change, save it and apply changes to resolve the issue
Click Save Peer (button)
Click Apply Changes (button)
Click Status (tab)
Click Show Peers (button)
Peer connection shows established.
![Screenshot 2021-06-11 at 08 55 59](https://user-images.githubusercontent.com/85263005/121714911-2c780b00-ca93-11eb-90b3-b2d904fbbe45.png)

**Comment by Tigger2014** [comment]
Are you able to change `us8500.nordvpn.com` to the IP as a test and see if it comes up at reboot?
The IP looks to be `62.182.99.1601` from my end but ping it to double check

**Comment by infosecmatters2021** [comment]
Thank you.
I changed the FQDN (us8500.nordvpn.com) to the IP (62.182.99.16) and it successfully connected after reboot.
I'll close this ticket.

**Comment by theonemcdonald** [comment]
I’m going to look into the DNS race issue here first thing next week. It’s something we need to handle better

**Comment by theonemcdonald** [comment]
@infosecmatters2021 

This is what I'm building. Default is 300 seconds (5 minutes), but is adjustable.

![image](https://user-images.githubusercontent.com/3102039/121920741-538a4300-cd06-11eb-8712-6ca0e0d60dc1.png)

**Comment by infosecmatters2021** [comment]
After a reboot, the handshake still show disconnected even after the endpoint DNS TTL period expires. 

I downloaded the latest version (zip file) then copied all files from the pkg and www f
![Screenshot 2021-06-14 at 11 51 10](https://user-images.githubusercontent.com/85263005/121944494-94368c00-cd07-11eb-933f-1b78a885e967.png)
![Screenshot 2021-06-14 at 11 50 59](https://user-images.githubusercontent.com/85263005/121944500-94cf2280-cd07-11eb-9987-df7304e898b3.png)
![Screenshot 2021-06-14 at 11 50 52](https://user-images.githubusercontent.com/85263005/121944503-9567b900-cd07-11eb-93ae-e3b7473e426d.png)


olders to my pfSense instance then rebooted it.

**Comment by theonemcdonald** [comment]
Would it be possible to get a nordvpn wireguard keypair from your for a few days for testing? Email me rcmcdonald91@gmail.com

**Comment by theonemcdonald** [comment]
Something new 
![image](https://user-images.githubusercontent.com/3102039/122266318-ac451180-cea7-11eb-904f-d16db8afad5d.png)
