### ISSUE TITLE
[BUG] GUI Install of 0.1.2_6 not installing new kmod

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#113]
Running pfSense+ 21.05 on SG-3100.
Previously running WireGuard package v0.1.2_1
Added repo via sh command.

GUI showed v0.1.2_6 update available with wireguard-tools-1.0.20210424 and wireguard-kmod-0.0.20210606.
Update applied. (see output below).

WireGuard VPN status shows:
pfSense-pkg-WireGuard ver 0.1.2_6
wireguard-kmod ver 0.0.20210503
wireguard-tools-lite  ver 1.0.20210424 installed

[UPDATE] I noticed that the wireguard-kmod-0.0.20210606 was also not installed on my pfSense 2.5.1 box as well. WireGuard Status shows that its at 0.0.20210503.

Upgrade Command Output:

>>> Upgrading pfSense-pkg-WireGuard... 
Updating mced repository catalogue...
mced repository is up to date.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
The following 2 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
	pfSense-pkg-WireGuard-0.1.2_6 [mced]
	pkg-1.16.3 [pfSense]

Number of packages to be reinstalled: 2

7 MiB to be downloaded.
[1/2] Fetching pkg-1.16.3.txz: .......... done
[2/2] Fetching pfSense-pkg-WireGuard-0.1.2_6.txz: .... done
Checking integrity... done (0 conflicting)
[1/2] Reinstalling pkg-1.16.3...
[1/2] Extracting pkg-1.16.3: .......... done
[2/2] Reinstalling pfSense-pkg-WireGuard-0.1.2_6...
[2/2] Extracting pfSense-pkg-WireGuard-0.1.2_6: .......... done
Removing WireGuard components...
Menu items... done.
Services... done.
Loading package instructions...
  Removing WireGuard early shell commands...done.
  Removing WireGuard interface group...done.
  Removing WireGuard temporary files...done.
  Keeping WireGuard configuration settings...done.
  Removing WireGuard Unbound access list...done.
  Destroying WireGuard tunnels...done.
  Stopping and removing the WireGuard service...done.
Saving updated package information...
overwrite!
Loading package configuration... done.
Configuring package components...
Loading package instructions...
Custom commands...
Executing custom_php_install_command()...
  Upgrading any existing WireGuard XML configuration...done.
  Installing WireGuard early shell commands...done.
  Creating WireGuard interface group...done.
  Creating WireGuard Unbound access list...done.
  Installing WireGuard service...done.
done.
Executing custom_php_resync_config_command()...done.
Menu items... done.
Services... done.
Writing configuration... done.
You may need to manually remove /usr/local/etc/pkg.conf if it is no longer needed.
>>> Cleaning up cache... done.
Success

**Comment by emikaadeo-git** [comment]
Same here on 2.5.1
For me solution to upgrade to `wireguard-kmod 0.0.20210606` was to run `pkg upgrade` from SSH

**Comment by vajonam** [comment]
This happens if you installed the kmod's manually in the first place. pkg remembers how they were installed. if you have installed it from the repo then it should upgrade as you expect.

**Comment by emikaadeo-git** [comment]
> This happens if you installed the kmod's manually in the first place.

That was my case. Thanks for clarifying.
