### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by korshakov** [theonemcdonald/pfSense-pkg-WireGuard#114]
Would there by any possibility to add 2 factor authentication which is implemented in TunSafe?
https://tunsafe.com/user-guide/2fa

As what it seems like all we have to do is to add this code on server side to the peer config:
RequireToken = totp-sha1:SECRET,digits=6,period=30,precision=15

**Comment by Tigger2014** [comment]
This is tunsafe only and implemented in their wireguard implementation, we are using the original version so this is not possible until the feature is upstream.

**Comment by theonemcdonald** [comment]
> so this is not possible <s>until the feature is upstream</s>.

Fixed it for you. I can't imagine this ever being added to WireGuard proper.

/s
