### ISSUE TITLE
[BUG] AllowedIPs not being applied

### ISSUE THREAD

**Issue by thecoolreaver** [theonemcdonald/pfSense-pkg-WireGuard#115]
**Describe the bug**
Some AllowedIPs are not being set, ending up as (none) which doesn't allow any traffic to flow through

**To Reproduce**
Unknown

**Expected behavior**
All AllowedIPs should be applied and not left with a empty field

**Screenshots**
![Screenshot 2021-06-17 17 45 27](https://user-images.githubusercontent.com/787159/122489214-fc999d80-cf93-11eb-9c11-ea2003a0e163.png)

**Version information (please complete the following information):**
 - PfSense: 2.5.2.r.20210617.1709 AND 2.5.1
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210606
 - pfSense-pkg-WireGuard: 0.1.2_6

**Additional context**

Shell Output - wg show tun_wg3
```
interface: tun_wg3
  public key: PUBLICKEY
  private key: (hidden)
  listening port: 51820

peer: PRIVATE1
  allowed ips: (none)
  transfer: 0 B received, 18.21 KiB sent
  persistent keepalive: every 30 seconds

peer: PRIVATE2
  allowed ips: 0.0.0.0/1, 128.0.0.0/1
  transfer: 0 B received, 11.27 KiB sent
  persistent keepalive: every 30 seconds
```

Shell Output - wg show tun_wg3
```
interface: tun_wg3
  public key: PUBLICKEY
  private key: (hidden)
  listening port: 51820

peer: PRIVATE1
  allowed ips: (none)
  transfer: 0 B received, 18.21 KiB sent
  persistent keepalive: every 30 seconds

peer: PRIVATE2
  allowed ips: 0.0.0.0/1, 128.0.0.0/1
  transfer: 0 B received, 11.27 KiB sent
  persistent keepalive: every 30 seconds
```

/usr/local/etc/wireguard/tun_wg3.conf
```
# This WireGuard config file has been created automatically. Do not edit!

# Description: VPN - World
[Interface]
PrivateKey = PRIVATEKEY
ListenPort = 51820

# Peer: Phone1
[Peer]
PublicKey = PRVIATE1
AllowedIPs = 128.0.0.0/1,0.0.0.0/1
PersistentKeepalive = 30

# Peer: Phone2
[Peer]
PublicKey = PRIVATE2
AllowedIPs = 128.0.0.0/1,0.0.0.0/1
PersistentKeepalive = 30
```

**Comment by theonemcdonald** [comment]
Not a bug,

You can't have overlapping allowedips per tunnel

**Comment by thecoolreaver** [comment]
I do feel like this is a bug tho as here is another config and they also show the same (none) and testing this via a normal wireguard server, it works with all AllowedIPs showing

![Screenshot 2021-06-17 18 05 32](https://user-images.githubusercontent.com/787159/122490542-1c7e9080-cf97-11eb-968c-d35eff212d86.png)


Shell Output - wg show tun_wg1
```
interface: tun_wg1
  public key: ----
  private key: (hidden)
  listening port: 51835

peer: ----
  endpoint: ----
  allowed ips: 92.168.35.0/24
  latest handshake: 1 second ago
  transfer: 424 B received, 1.40 KiB sent
  persistent keepalive: every 30 seconds

peer: ----
  allowed ips: (none)
  transfer: 0 B received, 2.75 KiB sent
  persistent keepalive: every 30 seconds

peer: ----
  allowed ips: (none)
  transfer: 0 B received, 2.75 KiB sent
  persistent keepalive: every 30 seconds

peer: ----
  allowed ips: 192.168.35.0/24
  transfer: 0 B received, 2.75 KiB sent
  persistent keepalive: every 30 seconds
```
