### ISSUE TITLE
Peer is not destroyed when moved to other tunnel

### ISSUE THREAD

**Issue by RafalArciszewski** [theonemcdonald/pfSense-pkg-WireGuard#116]
When there is an active peer on one tunnel and I move this peer to other tunnel the old one still is active and can transmit the data.

**Steps to reproduce the behavior**
create peer under tunnel 0
activate the peer and have constant transmision
move the peer to tunnel 1, change config ex. allowed ips
the old connection is still working

**Expected behavior**
The old peer connection should be disconnected

**Version information (please complete the following information):**
 - PfSense: Netgate SG-3100 21.05
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.1

Thank very much for the plugin its much better than original wireguard implementation.

Regards,
Rafał Arciszewski

**Comment by RafalArciszewski** [comment]
In addition when I delete the peer, the old one still is working. In the GUI status the peer name is empty
![obraz](https://user-images.githubusercontent.com/62645342/122539506-f81ec480-d027-11eb-80cd-04ab6343e938.png)

I have Keepalive active in peer configuration if it change anything.

**Comment by theonemcdonald** [comment]
Thanks. This has actually already been fixed and will be in the next PR with Netgate
