### ISSUE TITLE
[Feature] Wireguard status dashboard widget

### ISSUE THREAD

**Issue by tigattack** [theonemcdonald/pfSense-pkg-WireGuard#119]
A low priority feature request: A dashboard widget for WG status, similar to the OpenVPN or IPSEC dashboard widgets.

Thanks for all your work on this!

**Comment by theonemcdonald** [comment]
Definitely on the roadmap!

**Comment by tigattack** [comment]
Awesome, cheers!

**Comment by theonemcdonald** [comment]
Merged in the primitive widget from @GenericStudent ! Will build more on this as time goes on.

**Comment by theonemcdonald** [comment]
![image](https://user-images.githubusercontent.com/3102039/124515981-bd9a8300-ddae-11eb-975b-4e4fda6f7bf8.png)

Add some additional functionality to a backend stats collector that can now filter inactive peers so we can do this!

(Only shows the number of active peers, active within the last 5 minutes...the threshold could be a configurable option if there is a need for it to be configurable).

**Comment by theonemcdonald** [comment]
![image](https://user-images.githubusercontent.com/3102039/124625177-95ad2d00-de4b-11eb-8220-3148b9c60a8c.png)

The handshake activity threshold is now configurable. Default is 30 seconds, but can be adjusted. Setting the value to 0 will show all configured peers (i.e. both active and inactive).
