### ISSUE TITLE
[BUG] Static Route stop working on WireGuard Tunnel service restart or firewall reboot

### ISSUE THREAD

**Issue by jcarlosc88** [theonemcdonald/pfSense-pkg-WireGuard#122]
**Describe the bug**
The defined static route stop working if you stop/start the tunnel.

**To Reproduce**
Set the tunnel working to pass traffic site-to-site, and restart any of the ends, it will stop passing the traffic through.

**Expected behavior**
On a tunnel restart, or firewall reboot, the tunnel should start (and it does), and start passing all the traffic through the defined static routes and not the default gateway.

**Version information (please complete the following information):**
 - PfSense: 2.5.1
 - WireGuard-tools: wireguard-tools-lite-1.0.20210424.txz
 - WireGuard-kmod: wireguard-kmod-0.0.20210606.txz
 - pfSense-pkg-WireGuard: pfSense-pkg-WireGuard-0.1.2_6.txz

**Additional context**
It's that normal, or there is something that i need to configure on pfsense to force the traffic go through a static route all the time, even if the tunnel its down.

**Comment by theonemcdonald** [comment]
Possible that we need to reconfigure routing subsystem in addition to pf (and dpinger, and unbound).

**Comment by jcarlosc88** [comment]
yeah.....if i go to the static route, disable and enable again, all start to work again as it should

**Comment by jcarlosc88** [comment]
![Status WireGuard](https://user-images.githubusercontent.com/80071541/122958253-b015df80-d350-11eb-9d19-44adc6ce96ee.png)
![System Routing Gateways](https://user-images.githubusercontent.com/80071541/122958288-b7d58400-d350-11eb-978c-3ca9efec4821.png)
![System Routing Static Routes](https://user-images.githubusercontent.com/80071541/122958289-b86e1a80-d350-11eb-958c-cb867e2147cd.png)
![VPN WireGuard Peers Edit](https://user-images.githubusercontent.com/80071541/122958294-b906b100-d350-11eb-86bf-58f9d9b67bf4.png)
![VPN WireGuard Tunnels Edit](https://user-images.githubusercontent.com/80071541/122958301-b99f4780-d350-11eb-9265-94f899a03e7f.png)


Hope this helps!!

**Comment by theonemcdonald** [comment]
Thanks. Will investigate this and circle back

**Comment by jcarlosc88** [comment]
Thanks bro....and keep going this great work.

Cheers!!

**Comment by Tigger2014** [comment]
Do you have gateway monitoring setup for this route in any way?

Can you confirm if System>Advanced>Miscellaneous
`Do not create rules when gateway is down`

Is ticked?

**Comment by jcarlosc88** [comment]
![System Advanced Miscellaneous](https://user-images.githubusercontent.com/80071541/122962710-ad68b980-d353-11eb-98b2-abc63720cba5.jpg)
![System Routing Gateways Edit](https://user-images.githubusercontent.com/80071541/122962722-b063aa00-d353-11eb-8273-dfbea85d65eb.png)


isn't ticked that option, i have it like this, is that wrong?

**Comment by mrdziobaty** [comment]
It makes no difference whether 'Do not create rules when gateway is down' is enabled or not. Re-saving one static route causes all static routes to start working again. pfSense 2.5.1

**Comment by theonemcdonald** [comment]
Did some closer looking to pfsense internals, I think I see what's going on. Will experiment this weekend

**Comment by theonemcdonald** [comment]
@mrdziobaty Can you test v0.1.4_6 and try again?

You can download binaries here: http://packages.mced.tech/packages/

**Comment by mrdziobaty** [comment]
0.1.4_6 works great. Static routes work after service restarts, and reboots. Thanks!
