### ISSUE TITLE
[BUG] Peer data not showing under Tunnels > Show Peers

### ISSUE THREAD

**Issue by jvolkenant** [theonemcdonald/pfSense-pkg-WireGuard#123]
**Describe the bug**
Since installing 0.1.3, the data on peers are no longer shown under the Tunnels Show peers expansion

**To Reproduce**
With pfSense-pkg-WireGuard-0.1.3.txz
VPN > WireGuard > Tunnels Tab.
Click light blue "Show Peers" button.
Peers used to show here on pfSense-pkg-WireGuard-0.1.2_6.txz, but not with pfSense-pkg-WireGuard-0.1.3.txz
They are however shown under the Status> "Show Peers" screen

**Expected behavior**
Details on Peers on the Tunnels tab should show the data like it does under peers on the Status tab

**Screenshots**
With pfSense-pkg-WireGuard-0.1.3.txz
![image](https://user-images.githubusercontent.com/10521453/122957311-a8e1d800-d336-11eb-8c0d-a3960be6c26f.png)
Reisntalling pfSense-pkg-WireGuard-0.1.2_6.txz
![image](https://user-images.githubusercontent.com/10521453/122957805-260d4d00-d337-11eb-84d4-1f1c1ed61fc7.png)

**Version information (please complete the following information):**
 - PfSense: 2.5.1-RELEASE
 - WireGuard-tools-lite: 1.0.20210424
 - WireGuard-kmod: 0.0.20210606
 - pfSense-pkg-WireGuard: 0.1.3

**Comment by theonemcdonald** [comment]
Can you upgrade to 2.5.2? I'm not actively testing against 2.5.1 anymore.

**Comment by jvolkenant** [comment]
Looking better, Now the Public Keys show up in the peers area, but the Allowed IP's do not
https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/e088bc9fd851d19d1b2216984ed139a0584af2c1/net/pfSense-pkg-WireGuard/files/usr/local/www/wg/vpn_wg_tunnels.php#L227

works with
```
  <td><?=wg_generate_peer_allowedips_popup_link(wg_get_peer_idx($peer['publickey'], $peer['tun']))?></td>

```

**Comment by theonemcdonald** [comment]
eh poop... Fixed now. No need to use wg_get_peer_idx, the peer_idx is already available as $peer_idx within that loop.

**Comment by jvolkenant** [comment]
A right; very nice.  I used status_wireguard.php as my testing.

Thanks again for your hard work!
