### ISSUE TITLE
Site to Site

### ISSUE THREAD

**Issue by sampson2269** [theonemcdonald/pfSense-pkg-WireGuard#124]
I might be missing something but when trying to configure a site-to-site connection I don't see anywhere that I can enter the peer's address like before. 
<img width="662" alt="site to site" src="https://user-images.githubusercontent.com/76621894/123030271-c9924800-d39f-11eb-9dc2-0f1f4b436569.png">

**Comment by theonemcdonald** [comment]
This is a difference from the old UI.

Once setup the WireGuard tunnel and peers, go to Interface Assignments in pfSense and assigng that tun_wgX interface to pfSense. From there you can then add addresses, create gateways, policy route, etc. Make sure you create static routes to any networks reached via the tunnel (or use a dynamic routing protocol like OSPF or BGP, both work fine over WG).

**Comment by sampson2269** [comment]
Ya I figured I might be missing something, thanks for your help.
