### ISSUE TITLE
[BUG] packages.mced.tech is down

### ISSUE THREAD

**Issue by Dids** [theonemcdonald/pfSense-pkg-WireGuard#125]
**Describe the bug**
The installation url (https://packages.mced.tech) is down.

**To Reproduce**
Try to access the URL and notice it doesn't work (multiple locations report it as being down).

**Expected behavior**
I'd expect the URL to be up, so I could use it to setup the repository for pfSense.

**Comment by andrewluebke** [comment]
I'm also having issues with it.

**Comment by theonemcdonald** [comment]
Fixed.
