### ISSUE TITLE
Changing Keep Alive to null keeps the old value in config file

### ISSUE THREAD

**Issue by fsamareanu** [theonemcdonald/pfSense-pkg-WireGuard#126]
Steps to reproduce: Create tunnel and peer. Set timeout on peer to , let's say, 25. Activate changes. wg showconf tun_wgX shows something like this:

[Interface]
ListenPort = 12345
PrivateKey = Redacted

[Peer]
PublicKey = Redacted
AllowedIPs = 0.0.0.0/0
Endpoint = 4.4.4.4:12345
**PersistentKeepalive = 25**

Now edit peer and set keepalive to blank (not set). Save and activate changes. Then do the same wg showconf tun_wgX:

[Interface]
ListenPort = 12345
PrivateKey = Redacted

[Peer]
PublicKey = Redacted
AllowedIPs = 0.0.0.0/0
Endpoint = 4.4.4.4:12345
**PersistentKeepalive = 25**

As you can see persistent keepalive is still set although undefined in UI. However, conf.xml shows the old value of 25:

                                <peers>
                                        <wgpeer>
                                                <publickey>Redacted</publickey>
                                                <endpoint>4.4.4.4</endpoint>
                                                <allowedips>0.0.0.0/0</allowedips>
                                                <descr><![CDATA[MYTUNNEL]]></descr>
                                                **<persistentkeepalive>25</persistentkeepalive>**
                                                <presharedkey></presharedkey>
                                                <port>12345</port>
                                                <peerwgaddr></peerwgaddr>
                                        </wgpeer>
                                </peers>

Running 2.5.2 RC.

Edit: reinstalling the package somehow fixes the configuration and timeout isn't present anymore.

**Comment by theonemcdonald** [comment]
That XML structure is not right in general. We aren't using wgpeer

**Comment by fsamareanu** [comment]
You're right, that's probably leftovers from my old installation (I moved from 0.7 to 0.1.3 and it seems I screwed up the cleanup somewhere). However, I can reproduce this on my 2.6 installation as well (which is fresh).

**Comment by theonemcdonald** [comment]
Can you verify the correctness of your .conf files at ```/usr/local/etc/wireguard/tun_wgX.conf``` ?

**Comment by fsamareanu** [comment]
Hello,

The files seem to be correct.

**Comment by theonemcdonald** [comment]
Unfortunately, if the files are correct, then the issue is with WireGuard Tools. I've spent an inordinate amount of time working around 'expected behavior.' I'm going to keep this on the back burner, but a low priority atm. If you restart the service, you'll likely see the correct keepalive setting applied.

**Comment by theonemcdonald** [comment]
I fixed this. Will be in the next revision. 

I'm not happy with the fix, but it's the best I can do until I can find the time to write my own replacement for `wg syncconf` that isn't as strict.
