### ISSUE TITLE
[BUG] 0.1.4 on 2.6, wireguard service would not start

### ISSUE THREAD

**Issue by fsamareanu** [theonemcdonald/pfSense-pkg-WireGuard#127]
**Describe the bug**
Upgraded from 0.1.3 to 0.1.4. Wireguard service will not start from UI.

**To Reproduce**
Upgrade to latest wireguard package on 2.6 (latest). After upgrade wireguard service is stopped and cannot be started anymore.

**Expected behavior**
Service should start, tunnels should establish

**Screenshots**

**Version information (please complete the following information):**
 - PfSense: 2.6 (latest nightly)
 - WireGuard-tools: 20210424
 - WireGuard-kmod: 20210606
 - pfSense-pkg-WireGuard:  0.1.4

**Additional context**

snip of xml:

                <wireguard>
                        <config></config>
                        <tunnels>
                                <item>
                                        <addresses></addresses>
                                        <name>tun_wg0</name>
                                        <enabled>yes</enabled>
                                        <descr><![CDATA[REDACTED]]></descr>
                                        <listenport>51820</listenport>
                                        <privatekey>REDACTED</privatekey>
                                        <publickey>REDACTED</publickey>
                                        <mtu>1420</mtu>
                                </item>
                        </tunnels>
                        <peers>
                                <item>
                                        <allowedips>
                                                <row>
                                                        <address>192.168.0.0</address>
                                                        <mask>16</mask>
                                                        <descr></descr>
                                                </row>
                                                <row>
                                                        <address>10.0.0.0</address>
                                                        <mask>8</mask>
                                                        <descr></descr>
                                                </row>
                                        </allowedips>
                                        <enabled>yes</enabled>
                                        <tun>tun_wg0</tun>
                                        <descr><![CDATA[REDACTED]]></descr>
                                        <persistentkeepalive>25</persistentkeepalive>
                                        <publickey>REDACTED</publickey>
                                        <presharedkey></presharedkey>
                                </item>
                        </peers>
                </wireguard>

[2.6.0-DEVELOPMENT][root@XXX]/usr/local/etc/rc.d: bash -x wireguardd start
+ case $1 in
+ rc_start
+ /usr/local/bin/php_wg -f /usr/local/pkg/wireguard/wg_service.inc start
Unable to start WireGuard service

**Comment by tcquade** [comment]
I ran into the same problem pfsense 2.5.2-RC wg 0.1.4

To resolve I went to Status > WireGuard > Tunnels > Edit and uncheck Enable Tunnel > Save then checked Enable Tunnel > Save and the tunnel then came to life. 

In short, I toggled the Tunnel off > save then on > save.

Ted

**Comment by theonemcdonald** [comment]
Fix will be pushed tomorrow

**Comment by fsamareanu** [comment]
> I ran into the same problem pfsense 2.5.2-RC wg 0.1.4
> 
> To resolve I went to Status > WireGuard > Tunnels > Edit and uncheck Enable Tunnel > Save then checked Enable Tunnel > Save and the tunnel then came to life.
> 
> In short, I toggled the Tunnel off > save then on > save.
> 
> Ted

This won’t work if tunnel is assigned to an interface.

**Comment by gshaffer1** [comment]
I'm seeing the same issue on 2.5.1. Don't want to tear my existing config apart just to disable and enable tunnels. Forced a reinstall of 0.1.3 from the command line!

**Comment by theonemcdonald** [comment]
Fixed in latest commits.

Logging framework is built. Basically every interaction we have with the system is recorded in a sort of 'transaction' history of what commands were executed, what was the return codes, output, etc. It's very rich.

It looks something like this:

```
Array
(
    [ret_code] => 0
    [errors] => Array
        (
        )

    [cmds] => Array
        (
            [0] => Array
                (
                    [cmd] => /sbin/ifconfig 'tun_wg0' 'inet' '10.1.25.1/24' 'add' 2>&1
                    [output] => Array
                        (
                        )

                    [ret_code] => 0
                    [errors] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [cmd] => /usr/local/bin/wg syncconf 'tun_wg0' '/usr/local/etc/wireguard/tun_wg0.conf'
                    [output] => Array
                        (
                        )

                    [ret_code] => 0
                    [errors] => Array
                        (
                        )

                )

        )
```
