### ISSUE TITLE
[BUG] Peer page triggers PHP parse error (v0.1.4_1)

### ISSUE THREAD

**Issue by Dids** [theonemcdonald/pfSense-pkg-WireGuard#129]
**Describe the bug**
Adding or editing a peer produces a PHP error:
```
PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in /usr/local/www/wg/vpn_wg_peers_edit.php on line 221
```

**To Reproduce**
Add or edit a peer.

**Expected behavior**
No error and should show the peer page instead.

**Version information (please complete the following information):**
 - PfSense: 2.5.1-RELEASE (amd64)
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210606
 - pfSense-pkg-WireGuard: 0.1.4_1

**Comment by theonemcdonald** [comment]
Fixed
