### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rofowollmar** [theonemcdonald/pfSense-pkg-WireGuard#130]
**Describe the bug**
Cannot edit the peer configuration and the service fails to start.

**To Reproduce**
Could provice configuration regarding Wireguard if needed, but it was the same bug every time I rebooted.

**Expected behavior**
Open the peer configuration and make changes, the service wireguard should start and function as with the 0.1.3 version.

**Screenshots**
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in /usr/local/www/wg/vpn_wg_peers_edit.php on line 221

**Version information (please complete the following information):**
 - PfSense: 2.5.1-RELEASE (amd64)
 - WireGuard-tools: wireguard-tools-lite-1.0.20210424
 - WireGuard-kmod: wireguard-kmod-0.0.20210606
 - pfSense-pkg-WireGuard:  pfSense-pkg-WireGuard-0.1.4_1 

**Additional context**

**Comment by theonemcdonald** [comment]
Fixed in #129 I just kicked off a new build. should be built soon.
