### ISSUE TITLE
[BUG] ACB causes slow startup of tunnels

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#131]
After updating to v0.1.4_2, WireGuard Service not starting (again)!

pfSense 2.5.1, updating from v0.1.3 via the Package Manager GUI.

I'll leave v0.1.4_2 install for a little while, what Info do you want to troubleshoot?

**Comment by theonemcdonald** [comment]
Check Settings page?

**Comment by vajonam** [comment]
@gshaffer1  in your config please add the `<enable>on</enable>` 

```
			<config>
				<keep_conf>yes</keep_conf>
				<hide_secrets></hide_secrets>
				<resolve_interval>300</resolve_interval>
				<resolve_interval_track>yes</resolve_interval_track>
				<enable>on</enable>
			</config>
```

**Comment by theonemcdonald** [comment]
I'm mulling through this now. hang tight

**Comment by gshaffer1** [comment]
> I'm mulling through this now. hang tight

Looking at the WireGuard Setting page, "Enable" is NOT checked and it won't let me check it because I have assigned tunnels. I will try adding "<enable>on</enable>" to the config as vajonam suggested.

<img width="1157" alt="Screen Shot 2021-06-28 at 7 38 27 AM" src="https://user-images.githubusercontent.com/43114946/123655936-4d0ac980-d7e4-11eb-9311-c5e4d3a249c9.png">

**Comment by theonemcdonald** [comment]
Yep I see it, writing a fix for this right now.

**Comment by gshaffer1** [comment]
> @gshaffer1 in your config please add the `<enable>on</enable>`
> 
> ```
> 			<config>
> 				<keep_conf>yes</keep_conf>
> 				<hide_secrets></hide_secrets>
> 				<resolve_interval>300</resolve_interval>
> 				<resolve_interval_track>yes</resolve_interval_track>
> 				<enable>on</enable>
> 			</config>
> ```

Looking at my config.xml, something is not right. Here is the beginning of the wireguard section:
               <wireguard>
                        <config></config>
                        <tunnels>


Did the config settings get deleted as part of the update?

I'll manually add them.

**Comment by vajonam** [comment]
@gshaffer1 fix is just in ... you will not need to do this. that was just an interim fix...

**Comment by vajonam** [comment]
@gshaffer1  it will be in the the _3 version.

**Comment by theonemcdonald** [comment]
I'm curious about the <config></config> tree... is that actually being dumped between upgrades? (It shouldn't)

**Comment by gshaffer1** [comment]
> I'm curious about the `<config></config>` tree... is that actually being dumped between upgrades? (It shouldn't)

Manually adding the config section, I was able to get my wireguard tunnels running, but I had to restart the service sever times before all of the tunnels came back up.

**Comment by vajonam** [comment]
hmm.. not sure why you need to start up several times, it might take a few seconds for it go through and bring up the tunnels. I have about 3 they come back within a few seconds, if you have lot more just waiting should have worked.

**Comment by theonemcdonald** [comment]
The rate limiting step is restarting unbound and dpinger, the actual WireGuard parts are quick.

**Comment by gshaffer1** [comment]
> hmm.. not sure why you need to start up several times, it might take a few seconds for it go through and bring up the tunnels. I have about 3 they come back within a few seconds, if you have lot more just waiting should have worked.

I have 4 tunnels. 1 came back up right away, I waited about 3-4 minutes before restarting the service.

**Comment by theonemcdonald** [comment]
came back up as in handshaking or just not listed at all under Status page?

(btw, feel free to jump on discord too)

**Comment by gshaffer1** [comment]
> came back up as in handshaking or just not listed at all under Status page?
> 
> (btw, feel free to jump on discord too)

Kind of hard to tell what was going on with out some logging. I was looking a the WireGuard Status page and refreshing it. It only listed 1 tunnel for a long period, then I restarted it.

**Comment by gshaffer1** [comment]
> I'm curious about the `<config></config>` tree... is that actually being dumped between upgrades? (It shouldn't)

I looked at a config.xml from 10 days ago that I saved. it didn't have anything in the `<config></config>` section either, just the tunnel and peer definitions.

**Comment by theonemcdonald** [comment]
Any idea what your upgrade path looked like? What version to what version?

**Comment by theonemcdonald** [comment]
@vajonam can we close?

**Comment by vajonam** [comment]
Yes I think so. Works for me on both upgrade from 0.1.4_2 to _3 and 0.1.2_6 to 0.1.4_3

**Comment by hjaltioj** [comment]
I cant connect now after update???? no handshake is made???

**Comment by theonemcdonald** [comment]
Service running?

**Comment by gshaffer1** [comment]
> Any idea what your upgrade path looked like? What version to what version?

Up until v0.1.1 I was side loading it by downloading the packages from your GitHub site and installing via the command line. After that, I was loading from the special repo.

**Comment by theonemcdonald** [comment]
Service should start in all situations, assuming you have the service enabled or if you have an assigned tunnel, which forces the service to be enabled

**Comment by hjaltioj** [comment]
it works today? wierd, havent restart or anything. now my pc gets the handshake. :)

**Comment by vajonam** [comment]
Handshakes only occur when you pass data through the tunnel. If your not
using the tunnel it might not need to handshake. Also handshake is not a
great indicator of tunnel being up. For this reason.

**Comment by theonemcdonald** [comment]
When you say one tunnel came up, are we talking handshakes or did the Status page only show one tunnel?

**Comment by gshaffer1** [comment]
> When you say one tunnel came up, are we talking handshakes or did the Status page only show one tunnel? Handshakes only occur when there is actually traffic to pass, so it's possible that tunnels can stay dormant for a while until they are needed.

The tunnel that has come up first has been the one I have for a mobile clients, since I had none connected I doubt there were any handshakes happening. The other 3 were site-to-site tunnels with keep-alive set to 30 seconds.

**Comment by theonemcdonald** [comment]
When you click on the status page, do you see entries for all 4?

**Comment by gshaffer1** [comment]
> When you click on the status page, do you see entries for all 4?

After the update and the first manual restart of the service, I have only seen 1 tunnel listed on the status page, the 1 for mobile clients. If I refresh the page or switch to another page and come back, I see the same tunnel. After I restart the service a second time, the other tunnels will show up, usually 1 at a time.

**Comment by theonemcdonald** [comment]
start the service manually from the CLI using `service wireguardd start`, it will spew output. What does it show?

**Comment by gshaffer1** [comment]
> start the service manually from the CLI using `service wireguardd start`, it will spew output. What does it show?

"WireGuard service is already running"

I'll try this with the next package update and provide any output. No issue if you close this thread, I'll open a new one if the problem happens again on the next update.

**Comment by theonemcdonald** [comment]
```service wireguardd stop``` then ```service wireguardd start```

or 

```service wireguardd restart```

**Comment by Tigger2014** [comment]
@gshaffer1 We have been discussing internally.

Would it be possible for you to jump onto Discord with us to help us identify this a bit quicker
https://discord.gg/7ZsUY4Ja

Feel free to join from  a browser and post a message on arrival, we will invite you to a debug channel.

**Comment by Tigger2014** [comment]
https://github.com/pfsense/pfsense/blob/d1b2d749cc977f95087dda56887e49621da989c2/src/etc/inc/config.lib.inc#L587

Adjust calls to write_config to not ACB until the last one

**Comment by gshaffer1** [comment]
> https://github.com/pfsense/pfsense/blob/d1b2d749cc977f95087dda56887e49621da989c2/src/etc/inc/config.lib.inc#L587
> 
> Adjust calls to write_config to not ACB until the last one

Noticed that v0.1.4_4 was available, updated via the package manager GUI. Worked great! The tunnels dropped, the WireGuard Service was automatically restarted and all of the tunnels came back up within 20-30 seconds.

**Comment by theonemcdonald** [comment]
Good deal, thanks for your help

**Comment by theonemcdonald** [comment]
Latest code contains some preliminary optimizations to speed things up with ACB enabled.
