### ISSUE TITLE
Can't Assign the Same Public Key to Multiple Peers on Same Tunnel

### ISSUE THREAD

**Issue by FreeWillyB** [theonemcdonald/pfSense-pkg-WireGuard#137]
ISSUE: The current validation will not allow the user to add the same public key to multiple peers on the same tunnel.

USE CASE: I have two sites which both have two WAN connections. In order to create redundancy, I want to create a single tunnel on both end, and then add the WAN1 and WAN2 IP addresses of the remote site as peers under the same tunnel. This worked in the kernel implementation of WireGuard, but it appears that the current validation is assuming that the user likely did not want to use the same public key and made a typo. However, in my use case, it IS intended. If I need to create two tunnels, then I can no longer use the benefits of the cryptokey routing in WireGuard and must relay on some other slower protocol resulting in decreased performance.

DESIRED OUTCOME: Instead of flat out denying the user the ability to add duplicate public keys, perhaps it would be better add a warning pop up asking the user "Did you REALLY mean to do this?" 

PfSense+ 21.05 
WireGuard 0.1.1

**Comment by theonemcdonald** [comment]
This is actually something I've been thinking about recently and you're correct, this is overly strict. Another use case would be user who want to configure a tunnel to a VPN provider (like Mullvad) and have several peers that can be used, failing over between them if one server goes down. Might be worth having some sort of priority metric associated with each peer too.

**Comment by FreeWillyB** [comment]
I'm not really sure how exactly to add the weighted metric, but that would be awesome! I know in my original testing of 2.5.0 beta, traffic was automatically sent out of the default gateway, so it worked out great. Unfortunately that piece was broken when it was released as GA and then ultimately removed entirely. If it works like the kernel did originally, then the metrics might not even be needed in the first place!

**Comment by FreeWillyB** [comment]
Just curious, but is there a way to manually bypass this in the conf file? I tried editing it, but it's looking like the package doesn't really like that. It wouldn't even add the peer to the tunnel, even though it was hard coded in the config file.

**Comment by FreeWillyB** [comment]
Interesting! Perhaps what I experienced previously was just more bugs in the kernel implementation. Because I was definitely able to add multiple peers with the same public key on a 2.5.0-beta and in 21.02 official release. It was awesome to let WG handle the crypto-key routing and define multiple endpoint addresses for the same remote server. Each server would then just use its default gateway to determine which WAN interface to send the traffic out of and the opposite end would respond to that same interface.

**Comment by Tigger2014** [comment]
The recommended way to do this currently would be separate tunnels and use gateway groups with monitoring to switch between the two for the covered networks
