### ISSUE TITLE
[BUG] 0.1.3 install error on 2.5.2

### ISSUE THREAD

**Issue by hockey6611** [theonemcdonald/pfSense-pkg-WireGuard#139]
**Describe the bug**
Install error resulting in package unable to be installed:
`pkg-static: Fail to create /usr/local/www/wg/js:Not a directory`

bug detailed in forum post here:
https://forum.netgate.com/topic/164913/wireguard-package-install-error-2-5-2-rc

**To Reproduce**
Install package using GUI on existing installation. Experienced 

**Expected behavior**
Package expected to install sucessfully.

**Screenshots**
See Forum post.

**Version information (please complete the following information):**
 - PfSense: 2.5.2 RELEASE
 - WireGuard package 0.1.3_1

**Additional context**
I am not a developer, but forum response from kalledk noted a [possible origin](https://github.com/pfsense/FreeBSD-ports/commit/569ae80a160c63ec16ef960a7e184fdb1914a274#diff-120d3bcec6a3246fffeac3893eb48c46605c9cef2fa0be3219c928e27b6518baL32-R31) of the issue. And suggested adding -p flag to mkdir.

**Comment by Tigger2014** [comment]
can you provide some shell tests for us?

You can run theses on the web ui  Diagnostics > command prompt > enter shell command

` ls -la /usr/local/www/wg`
& 
`ls -la /usr/local/www/`

**Comment by hockey6611** [comment]
Sure no problem!

![image](https://user-images.githubusercontent.com/28613898/125165676-fac39400-e165-11eb-80e0-48d5423f8c28.png)

`ls -la /usr/local/www/`

`total 7328
drwxr-xr-x  18 root  wheel    8192 Jul  7 22:56 .
drwxr-xr-x  16 root  wheel     512 Jul  7 22:59 ..
-rw-r--r--   1 root  wheel    6479 May 28 11:35 android-chrome-192x192.png
-rw-r--r--   1 root  wheel   19007 May 28 11:35 android-chrome-512x512.png
drwxr-xr-x   2 root  wheel     512 Jul  7 22:56 apple-touch
-rw-r--r--   1 root  wheel    6170 Dec  5  2019 apple-touch-icon.png
-rw-r--r--   1 root  wheel    7158 May 28 11:35 bandwidth_by_ip.php
-rw-r--r--   1 root  wheel     246 May 28 11:35 browserconfig.xml
drwxr-xr-x   3 root  wheel     512 Jul  7 22:56 classes
-rw-r--r--   1 root  wheel    4595 May 28 11:35 crash_reporter.php
drwxr-xr-x   2 root  wheel     512 Jul  7 22:56 csrf
-rw-r--r--   1 root  wheel    4317 May 28 11:35 csrf_error.php
drwxr-xr-x   3 root  wheel     512 Jul  7 22:56 css
-rw-r--r--   1 root  wheel    7962 May 28 11:35 diag_arp.php
-rw-r--r--   1 root  wheel    3328 May 28 11:35 diag_authentication.php
-rw-r--r--   1 root  wheel    9756 May 28 11:35 diag_backup.php
-rwxr-xr-x   1 root  wheel   13354 May 28 11:35 diag_command.php
-rw-r--r--   1 root  wheel    9202 May 28 11:35 diag_confbak.php
-rw-r--r--   1 root  wheel    3378 May 28 11:35 diag_defaults.php
-rw-r--r--   1 root  wheel    8630 May 28 11:35 diag_dns.php
-rw-r--r--   1 root  wheel    6392 Jun 10 22:17 diag_dump_states.php
-rw-r--r--   1 root  wheel    4469 May 28 11:35 diag_dump_states_sources.php
-rw-r--r--   1 root  wheel   11126 May 28 11:35 diag_edit.php
-rw-r--r--   1 root  wheel   13346 May 28 11:35 diag_gmirror.php
-rw-r--r--   1 root  wheel    2694 May 28 11:35 diag_halt.php
-rw-r--r--   1 root  wheel    2354 May 28 11:35 diag_limiter_info.php
-rw-r--r--   1 root  wheel    9321 May 28 11:35 diag_ndp.php
-rwxr-xr-x   1 root  wheel   17973 May 28 11:35 diag_packet_capture.php
-rw-r--r--   1 root  wheel    2475 May 28 11:35 diag_pf_info.php
-rw-r--r--   1 root  wheel    6329 May 28 11:35 diag_pftop.php
-rw-r--r--   1 root  wheel    5508 May 28 11:35 diag_ping.php
-rw-r--r--   1 root  wheel    4353 May 28 11:35 diag_reboot.php
-rw-r--r--   1 root  wheel    4441 May 28 11:35 diag_resetstate.php
-rw-r--r--   1 root  wheel    5198 May 28 11:35 diag_routes.php
-rw-r--r--   1 root  wheel    9714 May 28 11:35 diag_smart.php
-rw-r--r--   1 root  wheel    4355 May 28 11:35 diag_sockets.php
-rw-r--r--   1 root  wheel    6156 May 28 11:35 diag_states_summary.php
-rw-r--r--   1 root  wheel    2230 May 28 11:35 diag_system_activity.php
-rw-r--r--   1 root  wheel    8395 May 28 11:35 diag_tables.php
-rw-r--r--   1 root  wheel    8580 May 28 11:35 diag_testport.php
-rw-r--r--   1 root  wheel    5593 May 28 11:35 diag_traceroute.php
-rw-r--r--   1 root  wheel    5535 May 28 11:35 easyrule.php
-rw-r--r--   1 root  wheel     140 Jan 21 01:46 echo
-rw-r--r--   1 root  wheel    1162 May 28 11:35 favicon-16x16.png
-rw-r--r--   1 root  wheel    1842 May 28 11:35 favicon-32x32.png
-rw-r--r--   1 root  wheel   15086 May 28 11:35 favicon.ico
-rw-r--r--   1 root  wheel    6661 May 28 11:35 firewall_aliases.php
-rw-r--r--   1 root  wheel   15769 May 28 11:35 firewall_aliases_edit.php
-rw-r--r--   1 root  wheel    8341 May 28 11:35 firewall_aliases_import.php
-rw-r--r--   1 root  wheel   14147 May 28 11:35 firewall_nat.php
-rw-r--r--   1 root  wheel    9106 May 28 11:35 firewall_nat_1to1.php
-rw-r--r--   1 root  wheel    7695 May 28 11:35 firewall_nat_1to1_edit.php
-rw-r--r--   1 root  wheel   20449 May 28 11:35 firewall_nat_edit.php
-rw-r--r--   1 root  wheel    7471 May 28 11:35 firewall_nat_npt.php
-rw-r--r--   1 root  wheel    3864 May 28 11:35 firewall_nat_npt_edit.php
-rw-r--r--   1 root  wheel   16455 May 28 11:35 firewall_nat_out.php
-rw-r--r--   1 root  wheel   12713 Jun 10 13:09 firewall_nat_out_edit.php
-rw-r--r--   1 root  wheel   37026 May 28 11:35 firewall_rules.php
-rw-r--r--   1 root  wheel   72160 May 28 11:35 firewall_rules_edit.php
-rw-r--r--   1 root  wheel    7262 May 28 11:35 firewall_schedule.php
-rw-r--r--   1 root  wheel   31653 May 28 11:35 firewall_schedule_edit.php
-rw-r--r--   1 root  wheel   10933 May 28 11:35 firewall_shaper.php
-rw-r--r--   1 root  wheel    6435 May 28 11:35 firewall_shaper_queues.php
-rw-r--r--   1 root  wheel   11961 May 28 11:35 firewall_shaper_vinterface.php
-rw-r--r--   1 root  wheel    3481 May 28 11:35 firewall_shaper_wizards.php
-rw-r--r--   1 root  wheel    5243 May 28 11:35 firewall_virtual_ip.php
-rw-r--r--   1 root  wheel    9525 May 28 11:35 firewall_virtual_ip_edit.php
-rw-r--r--   1 root  wheel    2578 May 28 11:35 foot.inc
-rw-r--r--   1 root  wheel    1312 May 28 11:35 getqueuestats.php
-rw-r--r--   1 root  wheel    4918 May 28 11:35 getserviceproviders.php
-rw-r--r--   1 root  wheel    1337 May 28 11:35 getstats.php
-rw-r--r--   1 root  wheel   14703 May 28 11:35 graph.php
-rw-r--r--   1 root  wheel    7455 May 28 11:35 graph_cpu.php
-rw-r--r--   1 root  wheel   32317 May 28 11:35 guiconfig.inc
drwxr-xr-x   2 root  wheel    1024 Jul  6 17:23 haproxy
-rw-r--r--   1 root  wheel   29385 May 28 11:35 head.inc
-rw-r--r--   1 root  wheel   40231 Jun  4 14:09 help.php
-rw-r--r--   1 root  wheel    1888 May 28 11:35 ifstats.php
drwxr-xr-x   2 root  wheel     512 Jul  7 22:56 includes
-rw-r--r--   1 root  wheel   22573 May 28 11:35 index.php
-rwxr-xr-x   1 root  wheel  143640 May 28 11:35 interfaces.php
-rw-r--r--   1 root  wheel   19679 May 28 11:35 interfaces_assign.php
-rw-r--r--   1 root  wheel    4706 May 28 11:35 interfaces_bridge.php
-rw-r--r--   1 root  wheel   23388 May 28 11:35 interfaces_bridge_edit.php
-rw-r--r--   1 root  wheel    4270 May 28 11:35 interfaces_gif.php
-rw-r--r--   1 root  wheel    7780 May 28 11:35 interfaces_gif_edit.php
-rw-r--r--   1 root  wheel    4450 May 28 11:35 interfaces_gre.php
-rw-r--r--   1 root  wheel   10001 May 28 11:35 interfaces_gre_edit.php
-rw-r--r--   1 root  wheel    4540 May 28 11:35 interfaces_groups.php
-rw-r--r--   1 root  wheel    7730 May 28 11:35 interfaces_groups_edit.php
-rw-r--r--   1 root  wheel    4455 May 28 11:35 interfaces_lagg.php
-rw-r--r--   1 root  wheel   10575 May 28 11:35 interfaces_lagg_edit.php
-rw-r--r--   1 root  wheel    4790 May 28 11:35 interfaces_ppps.php
-rw-r--r--   1 root  wheel   38866 May 28 11:35 interfaces_ppps_edit.php
-rw-r--r--   1 root  wheel    5337 May 28 11:35 interfaces_qinq.php
-rw-r--r--   1 root  wheel   10160 May 28 11:35 interfaces_qinq_edit.php
-rw-r--r--   1 root  wheel    5691 May 28 11:35 interfaces_vlan.php
-rw-r--r--   1 root  wheel    6759 May 28 11:35 interfaces_vlan_edit.php
-rw-r--r--   1 root  wheel    4585 Jan  8  2021 interfaces_vxlan.php
-rw-r--r--   1 root  wheel    7886 Jan  8  2021 interfaces_vxlan_edit.php
-rw-r--r--   1 root  wheel    4148 May 28 11:35 interfaces_wireless.php
-rw-r--r--   1 root  wheel    5387 May 28 11:35 interfaces_wireless_edit.php
drwxr-xr-x   2 root  wheel     512 Jul  7 22:56 js
drwxr-xr-x   2 root  wheel     512 Apr 20  2020 lighttpd
-rw-r--r--   1 root  wheel    5563 May 28 11:35 logo.svg
-rw-r--r--   1 root  wheel     404 May 28 11:35 manifest.json
-rw-r--r--   1 root  wheel    3578 May 28 11:35 mstile-150x150.png
lrwxr-xr-x   1 root  wheel      25 Mar 19  2019 nginx -> /usr/local/www/nginx-dist
dr-xr-xr-x   2 root  wheel     512 Jul  6 17:22 nginx-dist
drwxr-xr-x   3 root  wheel    1536 Jun 24 01:57 pfblockerng
drwxr-xr-x   7 root  wheel     512 Jan 20 06:51 phpseclib
-rw-r--r--   1 root  wheel   19879 May 28 11:35 pkg.php
-rw-r--r--   1 root  wheel   43059 May 28 11:35 pkg_edit.php
-rw-r--r--   1 root  wheel    9435 May 28 11:35 pkg_mgr.php
-rw-r--r--   1 root  wheel   28528 May 28 11:35 pkg_mgr_install.php
-rw-r--r--   1 root  wheel    9120 May 28 11:35 pkg_mgr_installed.php
-rw-r--r--   1 root  wheel      45 Jan 21 02:12 privatekey
-rw-r--r--   1 root  wheel      45 Jan 21 02:12 publickey
-rw-r--r--   1 root  wheel   12541 Jan 13 14:24 rrd_fetch_json.php
-rw-r--r--   1 root  wheel    4730 May 28 11:35 safari-pinned-tab.svg
-rw-r--r--   1 root  wheel   15305 May 28 11:35 services_acb.php
-rw-r--r--   1 root  wheel    3481 May 28 11:35 services_acb_backup.php
-rw-r--r--   1 root  wheel    6122 Jun 10 13:09 services_acb_settings.php
-rw-r--r--   1 root  wheel   56585 May 28 11:35 services_captiveportal.php
-rw-r--r--   1 root  wheel    8821 May 28 11:35 services_captiveportal_filemanager.php
-rw-r--r--   1 root  wheel    9946 May 28 11:35 services_captiveportal_hasync.php
-rw-r--r--   1 root  wheel    6403 May 28 11:35 services_captiveportal_hostname.php
-rw-r--r--   1 root  wheel    6302 May 28 11:35 services_captiveportal_hostname_edit.php
-rw-r--r--   1 root  wheel    6151 May 28 11:35 services_captiveportal_ip.php
-rw-r--r--   1 root  wheel    7426 May 28 11:35 services_captiveportal_ip_edit.php
-rw-r--r--   1 root  wheel    7230 May 28 11:35 services_captiveportal_mac.php
-rw-r--r--   1 root  wheel    8418 May 28 11:35 services_captiveportal_mac_edit.php
-rw-r--r--   1 root  wheel   17299 May 28 11:35 services_captiveportal_vouchers.php
-rw-r--r--   1 root  wheel    7399 May 28 11:35 services_captiveportal_vouchers_edit.php
-rw-r--r--   1 root  wheel    4021 May 28 11:35 services_captiveportal_zones.php
-rw-r--r--   1 root  wheel    3410 May 28 11:35 services_captiveportal_zones_edit.php
-rw-r--r--   1 root  wheel    6468 May 28 11:35 services_checkip.php
-rw-r--r--   1 root  wheel    4685 May 28 11:35 services_checkip_edit.php
-rw-r--r--   1 root  wheel   65724 May 28 11:35 services_dhcp.php
-rw-r--r--   1 root  wheel   36941 May 28 11:35 services_dhcp_edit.php
-rw-r--r--   1 root  wheel    6431 May 28 11:35 services_dhcp_relay.php
-rw-r--r--   1 root  wheel   41521 May 28 11:35 services_dhcpv6.php
-rw-r--r--   1 root  wheel    7800 May 28 11:35 services_dhcpv6_edit.php
-rw-r--r--   1 root  wheel    5656 May 28 11:35 services_dhcpv6_relay.php
-rw-r--r--   1 root  wheel   16252 May 28 11:35 services_dnsmasq.php
-rw-r--r--   1 root  wheel    5419 May 28 11:35 services_dnsmasq_domainoverride_edit.php
-rw-r--r--   1 root  wheel    8079 May 28 11:35 services_dnsmasq_edit.php
-rw-r--r--   1 root  wheel    7427 May 28 11:35 services_dyndns.php
-rw-r--r--   1 root  wheel   20786 May 28 11:35 services_dyndns_edit.php
-rw-r--r--   1 root  wheel    5068 May 28 11:35 services_igmpproxy.php
-rw-r--r--   1 root  wheel    6646 May 28 11:35 services_igmpproxy_edit.php
-rw-r--r--   1 root  wheel   21794 May 28 11:35 services_ntpd.php
-rw-r--r--   1 root  wheel    8899 May 28 11:35 services_ntpd_acls.php
-rw-r--r--   1 root  wheel   25313 May 28 11:35 services_ntpd_gps.php
-rw-r--r--   1 root  wheel    7580 May 28 11:35 services_ntpd_pps.php
-rw-r--r--   1 root  wheel    4132 May 28 11:35 services_pppoe.php
-rw-r--r--   1 root  wheel   19297 May 28 11:35 services_pppoe_edit.php
-rw-r--r--   1 root  wheel    7138 May 28 11:35 services_rfc2136.php
-rw-r--r--   1 root  wheel    8940 May 28 11:35 services_rfc2136_edit.php
-rw-r--r--   1 root  wheel   17533 May 28 11:35 services_router_advertisements.php
-rw-r--r--   1 root  wheel    8674 Jun 24 21:15 services_servicewatchdog.php
-rw-r--r--   1 root  wheel    2480 Jun 24 21:15 services_servicewatchdog_add.php
-rw-r--r--   1 root  wheel   11208 May 28 11:35 services_snmp.php
-rw-r--r--   1 root  wheel   24972 May 28 11:35 services_unbound.php
-rw-r--r--   1 root  wheel   10410 May 28 11:35 services_unbound_acls.php
-rw-r--r--   1 root  wheel   23987 May 28 11:35 services_unbound_advanced.php
-rw-r--r--   1 root  wheel    6412 May 28 11:35 services_unbound_domainoverride_edit.php
-rw-r--r--   1 root  wheel    9200 May 28 11:35 services_unbound_host_edit.php
-rw-r--r--   1 root  wheel    6706 May 28 11:35 services_wol.php
-rw-r--r--   1 root  wheel    4105 May 28 11:35 services_wol_edit.php
drwxr-xr-x   2 root  wheel     512 Jul  9 16:57 shortcuts
-rw-r--r--   1 root  wheel    9724 May 28 11:35 shortcuts.inc
drwxr-xr-x   2 root  wheel     512 Jan 20 06:51 simplepie
-rw-r--r--   1 root  wheel     927 May 28 11:35 stats.php
-rw-r--r--   1 root  wheel   18518 May 28 11:35 status.php
-rw-r--r--   1 root  wheel   11054 May 28 11:35 status_captiveportal.php
-rw-r--r--   1 root  wheel    3436 May 28 11:35 status_captiveportal_expire.php
-rw-r--r--   1 root  wheel    3501 May 28 11:35 status_captiveportal_test.php
-rw-r--r--   1 root  wheel    4202 May 28 11:35 status_captiveportal_voucher_rolls.php
-rw-r--r--   1 root  wheel    4419 May 28 11:35 status_captiveportal_vouchers.php
-rw-r--r--   1 root  wheel    7364 May 28 11:35 status_carp.php
-rw-r--r--   1 root  wheel   15446 May 28 11:35 status_dhcp_leases.php
-rw-r--r--   1 root  wheel   16989 May 28 11:35 status_dhcpv6_leases.php
-rw-r--r--   1 root  wheel    5226 May 28 11:35 status_filter_reload.php
-rw-r--r--   1 root  wheel    6150 May 28 11:35 status_gateway_groups.php
-rw-r--r--   1 root  wheel    5143 May 28 11:35 status_gateways.php
-rw-r--r--   1 root  wheel    8979 May 28 11:35 status_graph.php
-rw-r--r--   1 root  wheel    1859 May 28 11:35 status_graph_cpu.php
-rw-r--r--   1 root  wheel   11266 May 28 11:35 status_interfaces.php
-rw-r--r--   1 root  wheel   21077 May 28 11:35 status_ipsec.php
-rw-r--r--   1 root  wheel    3795 May 28 11:35 status_ipsec_leases.php
-rw-r--r--   1 root  wheel    3701 May 28 11:35 status_ipsec_sad.php
-rw-r--r--   1 root  wheel    3170 May 28 11:35 status_ipsec_spd.php
-rw-r--r--   1 root  wheel    6505 May 28 11:35 status_logs.php
-rw-r--r--   1 root  wheel   35727 May 28 11:35 status_logs_common.inc
-rw-r--r--   1 root  wheel   12172 May 28 11:35 status_logs_filter.php
-rw-r--r--   1 root  wheel   12616 May 28 11:35 status_logs_filter_dynamic.php
-rw-r--r--   1 root  wheel    7849 May 28 11:35 status_logs_filter_summary.php
-rw-r--r--   1 root  wheel    6066 May 28 11:35 status_logs_packages.php
-rw-r--r--   1 root  wheel   21405 May 28 11:35 status_logs_settings.php
-rw-r--r--   1 root  wheel   11416 May 28 11:35 status_logs_vpn.php
-rw-r--r--   1 root  wheel   48188 Jan 13 14:24 status_monitoring.php
-rw-r--r--   1 root  wheel   12556 May 28 11:35 status_ntpd.php
-rw-r--r--   1 root  wheel   12048 May 28 11:35 status_openvpn.php
-rw-r--r--   1 root  wheel   12830 May 28 11:35 status_queues.php
-rw-r--r--   1 root  wheel    3778 May 28 11:35 status_services.php
-rw-r--r--   1 root  wheel    4922 May 28 11:35 status_unbound.php
-rw-r--r--   1 root  wheel    4125 May 28 11:35 status_upnp.php
-rw-r--r--   1 root  wheel    5631 May 28 11:35 status_wireless.php
-rw-r--r--   1 root  wheel   27355 May 28 11:35 system.php
-rw-r--r--   1 root  wheel   15007 May 28 11:35 system_advanced_admin.php
-rw-r--r--   1 root  wheel   15901 May 28 11:35 system_advanced_firewall.php
-rw-r--r--   1 root  wheel   14832 May 28 11:35 system_advanced_misc.php
-rw-r--r--   1 root  wheel   12589 May 28 11:35 system_advanced_network.php
-rw-r--r--   1 root  wheel   10957 May 28 11:35 system_advanced_notifications.php
-rw-r--r--   1 root  wheel    5789 May 28 11:35 system_advanced_sysctl.php
-rw-r--r--   1 root  wheel   31941 May 28 11:35 system_authservers.php
-rw-r--r--   1 root  wheel   26094 May 28 11:35 system_camanager.php
-rw-r--r--   1 root  wheel   54236 May 28 11:35 system_certmanager.php
-rw-r--r--   1 root  wheel    8569 May 28 11:35 system_certmanager_renew.php
-rw-r--r--   1 root  wheel   18660 May 28 11:35 system_crlmanager.php
-rw-r--r--   1 root  wheel    5797 May 28 11:35 system_gateway_groups.php
-rw-r--r--   1 root  wheel    9890 May 28 11:35 system_gateway_groups_edit.php
-rw-r--r--   1 root  wheel   13912 May 28 11:35 system_gateways.php
-rw-r--r--   1 root  wheel   14196 May 28 11:35 system_gateways_edit.php
-rw-r--r--   1 root  wheel   15926 May 28 11:35 system_groupmanager.php
-rw-r--r--   1 root  wheel    9604 May 28 11:35 system_groupmanager_addprivs.php
-rw-r--r--   1 root  wheel   10110 May 28 11:35 system_hasync.php
-rw-r--r--   1 root  wheel    9509 May 28 11:35 system_routes.php
-rw-r--r--   1 root  wheel    9383 May 28 11:35 system_routes_edit.php
-rw-r--r--   1 root  wheel    7437 May 28 11:35 system_update_settings.php
-rw-r--r--   1 root  wheel    6709 May 28 11:35 system_user_settings.php
-rw-r--r--   1 root  wheel   34337 May 28 11:35 system_usermanager.php
-rw-r--r--   1 root  wheel    9273 May 28 11:35 system_usermanager_addprivs.php
-rw-r--r--   1 root  wheel    3639 May 28 11:35 system_usermanager_passwordmg.php
-rw-r--r--   1 root  wheel   10282 May 28 11:35 system_usermanager_settings.php
-rw-r--r--   1 root  wheel    2137 May 28 11:35 upgrnotice.inc
-rw-r--r--   1 root  wheel    1754 May 28 11:35 uploadconfig.php
drwxr-xr-x  13 root  wheel     512 May 28 11:35 vendor
-rw-r--r--   1 root  wheel   23035 May 28 11:35 vpn_ipsec.php
-rw-r--r--   1 root  wheel    5272 May 28 11:35 vpn_ipsec_keys.php
-rw-r--r--   1 root  wheel    6863 May 28 11:35 vpn_ipsec_keys_edit.php
-rw-r--r--   1 root  wheel   26530 Jun  4 14:09 vpn_ipsec_mobile.php
-rw-r--r--   1 root  wheel   45354 May 28 11:35 vpn_ipsec_phase1.php
-rw-r--r--   1 root  wheel   36017 May 28 11:35 vpn_ipsec_phase2.php
-rw-r--r--   1 root  wheel   19937 May 28 11:35 vpn_ipsec_settings.php
-rw-r--r--   1 root  wheel   11540 May 28 11:35 vpn_l2tp.php
-rw-r--r--   1 root  wheel    3195 May 28 11:35 vpn_l2tp_users.php
-rw-r--r--   1 root  wheel    4395 May 28 11:35 vpn_l2tp_users_edit.php
-rw-r--r--   1 root  wheel   51850 May 28 11:35 vpn_openvpn_client.php
-rw-r--r--   1 root  wheel   23849 May 28 11:35 vpn_openvpn_csc.php
-rw-r--r--   1 root  wheel   45062 Jun 10 22:00 vpn_openvpn_export.php
-rw-r--r--   1 root  wheel   13894 Jun 10 22:00 vpn_openvpn_export_shared.php
-rw-r--r--   1 root  wheel   78553 May 28 11:35 vpn_openvpn_server.php
-rw-r--r--   1 root  wheel    6238 Feb 13 08:07 vpn_wg.php
-rw-r--r--   1 root  wheel   17036 Feb 13 08:07 vpn_wg_edit.php
-rw-r--r--   1 root  wheel      17 Jan 21 02:11 wg
drwxr-xr-x   5 root  wheel     512 May 28 11:35 widgets
-rw-r--r--   1 root  wheel   29850 May 28 11:35 wizard.php
drwxr-xr-x   2 root  wheel     512 Jul  7 22:56 wizards
-rw-r--r--   1 root  wheel   27422 May 28 11:35 xmlrpc.php`

**Comment by Tigger2014** [comment]
It looks like WG is not a directory

are you able to run `cd /usr/local/www/wg`

If not you might need to `rm -rf /usr/local/www/wg` and then attempt the install.

Somehow it looks like the wg folder is actually a file on your system.

**Comment by hockey6611** [comment]
Thank you for noticing that! I certainly is a file. I have no idea where it came from. Only thing I can think of, is one of the earlier package install attempts had an issue. I have not done anything in the shell on the system.

I also had the 2.5.0 RELEASE version of wireguard working prior to updating to the 2.5.2 RC, though that seems less likely of a reason.

Here are the contents of the file, does this give you any clue as to how it originated?
![image](https://user-images.githubusercontent.com/28613898/125182642-bd9ae880-e1dd-11eb-9065-2668b853320c.png)

I added a ".bak" to the file name instead of deleting it, just to test, and the WireGuard package installed successfully! I haven't attempted any configuration yet, but I presume everything will be fine. Thanks so much for helping narrow down my issue.

Let me know if you'd like me to close the issue since it is resolved for me, or if you want to keep it open to investigate the origin of this file.

**Comment by Tigger2014** [comment]
Not too sure where it came from.

As it solved we can close this issue.

Thanks for helping us get to the bottom of it
