### ISSUE TITLE
No routing after creation of interface [BUG]

### ISSUE THREAD

**Issue by MxMarl** [theonemcdonald/pfSense-pkg-WireGuard#140]
**Describe the bug**
If I leave the interface assignment at default (tun_wg0), add a peer, the connection works. Let's use the Allowed IP of the peer 10.0.0.2/32. 
But if I assign single tunnels to interfaces, for example tun_wg0 -> OPT4, and set correct firewall rules, it doesn't like to route anymore.

To undo the process, I delete the firewall rules on OPT4 and delete the interface. However, the routing does not work anymore. Solution is to temporarily change the Allowed IP of the peer to for example 10.0.0.2/31 and then to the default 10.0.0.2/32. Then the routing works again.

**To Reproduce**
- Create tunnel and peer
- Set FW rules under Firewall>Rules>WireGuard:
- IPv4* 10.0.0.2 * * *
- Assign tun_wg0 to OPT4
- IPv4* 10.0.0.2 * * *
- Delete this rule, and delete OPT4
- No more routing

**Expected behavior**
automatic refresh

**Version information (please complete the following information):**
 - PfSense: 2.5.2-RELEASE (amd64) | built on Fri Jul 02 15:33:00 EDT 2021 | FreeBSD 12.2-STABLE
 - WireGuard-tools:  1.0.20210424
 - WireGuard-kmod: 0.0.20210606_1
 - pfSense-pkg-WireGuard:  0.1.3_1

**Comment by Baker0052** [comment]
Got also Routing problems.
If i edit the Peers, the tunnel itself or restart wireguard the routing is broken.
To fix it i have to "save" 1 of my 2 static routes and hit "apply" - then its working again.

strange thing: routing table always shows the correct routes.

**Comment by theonemcdonald** [comment]
This is fixed in the latest 0.1.14 branch
