### ISSUE TITLE
[BUG] Wireguard not showing in Package Manager after upgrading pfsense to 2.5.2

### ISSUE THREAD

**Issue by kevindd992002** [theonemcdonald/pfSense-pkg-WireGuard#141]
**Describe the bug**
So when I was in 2.5.1, I used https://github.com/theonemcdonald/pfSense-repo-scripts/blob/main/install/install_repo.sh (which looks like it's not existing anymore and is replaced by other scripts) to install the unofficial repository package and then installed WG easily through the package manager. 

Yesterday, I decided to upgrade pfsense to 2.5.2. WG was at 0.1.4_6 before the upgrade. After upgrading to 2.5.2, WG is still working and was even upgraded to 0.1.4_12 but it does not show under Package Manager (installed or available) anymore. 

So should I use the remove_repo.sh to fix this or something? I don't want to mess up anything so I thought I'd ask.

**Screenshots**
![image](https://user-images.githubusercontent.com/3907957/125153280-2f931380-e185-11eb-9be0-6a53252344bb.png)

![image](https://user-images.githubusercontent.com/3907957/125153305-61a47580-e185-11eb-8d9f-c81413a03528.png)

**Comment by Tigger2014** [comment]
You have two options to fix this,

use pfsense official repo:

ensure under VPN>WireGuard>Settings Keep config is ticked then

- `pkg delete wireguard-tools-lite`
- `pkg delete pfSense-pkg-WireGuard`
-  `pkg delete wireguard-kmod`

Continue to use the dev repo:
 
- re run the install `curl -s https://packages.mced.tech/install/install_repo_252.sh | sh`


If you continue to use the dev repo it should show up as installed after re running the script above.

Please let us know if this fixes it.

**Comment by kevindd992002** [comment]
> 
> 
> You have two options to fix this,
> 
> use pfsense official repo:
> 
> ensure under VPN>WireGuard>Settings Keep config is ticked then
> 
>     * `pkg delete wireguard-tools-lite`
> 
>     * `pkg delete pfSense-pkg-WireGuard`
> 
>     * `pkg delete wireguard-kmod`
> 
> 
> Continue to use the dev repo:
> 
>     * re run the install `curl -s https://packages.mced.tech/install/install_repo_252.sh | sh`
> 
> 
> If you continue to use the dev repo it should show up as installed after re running the script above.
> 
> Please let us know if this fixes it.

Since the official pfsense repo has this WG package tagged as "experimental", do both repos always contain the latest release? If so, I'd rather go with using the official repo. So right after deleting those packages, the WG package will appear in Package Manager -> Available Packages and I just reinstall from there?

**Comment by Tigger2014** [comment]
Currently the official repo is not always upto with the dev one, more frequent builds are pushed within dev. However this may change in time.

**Comment by kevindd992002** [comment]
> Currently the official repo is not always upto with the dev one, more frequent builds are pushed within dev. However this may change in time.

Ok, then I'll go with the dev repo. Does that repo only consider packages related to wireguard?

What is the difference between the 251 and 252 install repo scripts?

**Comment by Tigger2014** [comment]
The repo only provides the packages needed by wireguard.

The difference between 251 and 252 scripts is which code base they were built against. 252 targeting the 252 release.

All packages are built and are on https://packages.mced.tech

**Comment by kevindd992002** [comment]
Ok, so I reinstalled the 252 scripts successfully:

```
[2.5.2-RELEASE][root@pfSense.condo.arpa]/root: curl -s https://packages.mced.tech/install/install_repo_252.sh | sh
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- /etc/inc/pkg-utils.inc.orig        2021-05-29 05:04:18.000000000 +0000
|+++ /etc/inc/pkg-utils.inc     2021-06-08 11:05:29.153780000 +0000
--------------------------
Patching file /etc/inc/pkg-utils.inc using Plan A...
Hunk #1 succeeded at 403.
Hunk #2 succeeded at 475.
Hunk #3 succeeded at 505.
done
Updating mced repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01
Fetching packagesite.txz: 100%    3 KiB   3.0kB/s    00:01
Processing entries: 100%
mced repository update completed. 7 packages processed.
Updating Unofficial repository catalogue...
Unofficial repository is up to date.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
```

But for some reason, the Wireguard package is still orange at Status -> Dashboard -> Installed packages;

![image](https://user-images.githubusercontent.com/3907957/125169933-0606d600-e1df-11eb-855d-45fc9f5c8964.png)

I reinstalled the package and it still won't turn black/updated in the Dashboard. Under System -> Package Manager -> Installed Packages though, it does seem to look like it's updated:

![image](https://user-images.githubusercontent.com/3907957/125169973-38b0ce80-e1df-11eb-84e7-87c6dcd9e428.png)

Any ideas?

**Comment by Tigger2014** [comment]
Can you try my earlier pkg delete commands and then a reinstall via the gui?

Might be related to a switch of repos.

**Comment by kevindd992002** [comment]
I just tried that and it didn't fix it. Also, the 2nd command is not needed since the 1st command already takes care of uninstalling `pfSense-pkg-WireGuard`:

```
[2.5.2-RELEASE][root@pfSense.condo.arpa]/root: pkg delete wireguard-tools-lite
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 2 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        pfSense-pkg-WireGuard: 0.1.4_12
        wireguard-tools-lite: 1.0.20210424

Number of packages to be removed: 2

Proceed with deinstalling packages? [y/N]: y
[1/2] Deinstalling pfSense-pkg-WireGuard-0.1.4_12...
Removing WireGuard components...
Menu items... done.
Services... done.
Loading package instructions...
  Removing WireGuard early shell commands...done.
  Removing WireGuard interface group...done.
  Removing WireGuard temporary files...done.
  Keeping WireGuard configuration settings...done.
  Removing WireGuard Unbound access list...done.
  Destroying WireGuard tunnels...done.
  Stopping and removing the WireGuard service...done.
[1/2] Deleting files for pfSense-pkg-WireGuard-0.1.4_12: 100%
Removing WireGuard components...
Configuration... done.
[2/2] Deinstalling wireguard-tools-lite-1.0.20210424...
[2/2] Deleting files for wireguard-tools-lite-1.0.20210424:  28%
wireguard-tools-lite-1.0.20210424: missing file /usr/local/man/man8/wg.8.gz
[2/2] Deleting files for wireguard-tools-lite-1.0.20210424: 100%
[2.5.2-RELEASE][root@pfSense.condo.arpa]/root: pkg delete pfSense-pkg-WireGuard
No packages matched for pattern 'pfSense-pkg-WireGuard'

Checking integrity... done (0 conflicting)
1 packages requested for removal: 0 locked, 1 missing
[2.5.2-RELEASE][root@pfSense.condo.arpa]/root: pkg delete wireguard-kmod
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        wireguard-kmod: 0.0.20210606

Number of packages to be removed: 1

Proceed with deinstalling packages? [y/N]: y
[1/1] Deinstalling wireguard-kmod-0.0.20210606...
[1/1] Deleting files for wireguard-kmod-0.0.20210606: 100%
```

**Comment by Tigger2014** [comment]
Ok, we will have to see if we can reproduce to see what's causing this. 

We will update you if we find anything

**Comment by Tigger2014** [comment]
One last thing if you dont mind.

Please provide the output of 
`cat /usr/local/etc/pkg/repos/00_WireGuard.conf`

**Comment by kevindd992002** [comment]
Thanks. FWIW, I tried the same on my other pfSense box and it did the same exact thing. From that 2nd box, I tried using the GUI to uninstall the 3 packages and reinstalled using the GUI again, same thing. This is what I see when I hover the + button in the dashboard:

![image](https://user-images.githubusercontent.com/3907957/125171966-92b69180-e1e9-11eb-8bc7-4c839e59613e.png)

Content of the conf file:

```
[2.5.2-RELEASE][root@pfSense.condo.arpa]/root: cat /usr/local/etc/pkg/repos/00_WireGuard.conf
FreeBSD: { enabled: no } mced: { url: "http://packages.mced.tech/packages/freebsd_12-2_amd64-ng_ports_252", mirror_type: "http" , signature_type: "pubkey", pubkey: "/usr/local/etc/ssl/wireguard.crt", enabled: yes}
```

**Comment by Tigger2014** [comment]
What unofficial repo do you have enabled as im not seeing that repo update on my box, It possibly is that?

```
[2.5.2-RELEASE][root@pf01.local]/: pkg update
Updating mced repository catalogue...
mced repository is up to date.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
```

**Comment by kevindd992002** [comment]
> 
> 
> What unofficial repo do you have enabled as im not seeing that repo update on my box, It possibly is that?
> 
> ```
> [2.5.2-RELEASE][root@pf01.local]/: pkg update
> Updating mced repository catalogue...
> mced repository is up to date.
> Updating pfSense-core repository catalogue...
> pfSense-core repository is up to date.
> Updating pfSense repository catalogue...
> pfSense repository is up to date.
> All repositories are up to date.
> ```

I don't have any other unofficial repo other than the one from the scripts that you have. Originally, I used the install_repo.sh (without the 251 and 252 suffixes) script a few months ago when I started using WG on pfsense 2.5.1.

**Comment by Tigger2014** [comment]
@kevindd992002 are you able to jump onto discord? I will move you to a debug channel to help look into this more quickly

https://discord.gg/amAB87Cu

**Comment by kevindd992002** [comment]
Yes, I just joined. I'll wait for you to move me to the debug channel.

**Comment by Tigger2014** [comment]
@kevindd992002 I now can no longer reproduce this issue, Can you try in an incognito window, Just trying to work out how to make this reproducible on my side.

**Comment by Tigger2014** [comment]
This was a tricky one to track down :)

Please remove and re-add the repo, This should re-patch pfsense to deal with this now the package is in both repos.
Note: the package name is the GUI should now show up as WireGuard Dev if using the dev repo.
**Remove Repo**
`curl -s https://packages.mced.tech/install/remove_repo.sh | sh`
**Add repo**
`curl -s https://packages.mced.tech/install/install_repo_252.sh | sh`


Let me know if this sorts it for you.

**Comment by kevindd992002** [comment]
We are in good shape now :)

![image](https://user-images.githubusercontent.com/3907957/125182881-798efe80-e244-11eb-82ad-dc24281729f7.png)

So was it conflicting with the package in the official repo because it has the same package name?

**Comment by Tigger2014** [comment]
Yeah when pkg queries what versions are available  from the repos it lists each version which is not something pfsense expects as a pkg is not normally in two places.

This was causing pkg manager to join the two version strings together as one and hence the update needed is shown.

The name change is 100% cosmetic and only applies in the gui to help users know where the package came from.

**Comment by kevindd992002** [comment]
@Tigger2014 So when we were troubleshooting this a few days ago, I applied the [fix](https://github.com/theonemcdonald/pfSense-pkg-WireGuard/issues/141#issuecomment-877713119) to the pfsense box in Site B (from my other issue) first. The following day, I applied the same fix to the pfsense box in Site A. Everything was working fine. The package showed WireGuard Dev for both boxes.

Today, I checked Site B pfsense and it showed me that it needed an update (orange in dashboard). I upgraded the package to 0.1.5 and everything went great. In Site A pfsense, however, this is what I see:

Dashboard:
![image](https://user-images.githubusercontent.com/3907957/125880887-cf96ad2b-b2a4-42ec-85b5-b50311a00c3b.png)

Package manager -> installed packages:
![image](https://user-images.githubusercontent.com/3907957/125880978-230d5f9a-9c53-4314-9d95-08ae27ab25ce.png)

When I click the upgrade icon:
![image](https://user-images.githubusercontent.com/3907957/125881011-771d6357-ef2a-4a8c-836d-61f24410e13d.png)

Because of the inconsistency I saw, I did not proceed with the upgrade yet. I tried applying the same fix but that did not solve the issue. I decided to just proceed with the upgrade anyway. Surprisingly, that fixed the issue. It's now back to showing me WireGuard Dev 0.1.5 on both GUI sections.

Any idea what happened?

**Comment by Tigger2014** [comment]
Did you run the remove repo and repo install script today on site A, it looks to me like the patch was outdated.

**Comment by kevindd992002** [comment]
I did but only AFTER I saw the issue. Running both those scripts did not do anything. Which patch was outdated?

Got it, I'll continue monitoring.

**Comment by Tigger2014** [comment]
Most likely [https://packages.mced.tech/install/25_unofficial_packages_list.patch]
