### ISSUE TITLE
WIREGUARD PFSENSE SITE TO SITE

### ISSUE THREAD

**Issue by jimmyparr** [theonemcdonald/pfSense-pkg-WireGuard#142]
WHEN CREATING SITE TO SITE, TRAFFIC ONLY ACCES TUNNEL ITSELF 
10.100.100.1 CAN PING 10.100.100.2 AND VICE VERSA
BUT TRAFFIC FROM SUBNET CAN'T PING OTHER SUBNET.
SITE "A" SUBNET CAN'T REACH SITE "B" SUBNET
THE ART OF ALL RULE WHERE DONE 
- INTERFACE ASSIGMENT
- FIREWALL RULE
-  ROUTING DEFAULT NOT AUTOMATIC

BE AWARE THAT THE SAME CONFIG WAS WORKING AS EXPECTED IN VERSION 2.5 WHEN EVERY THING SUPPOSE TO BE A BIG DRAMA.

PFSENSE 2.5.2 
WIREGUARD 0.1.3_1
wireguard-tools-1.0.20210424
wireguard-kmod-0.0.20210606_1 

THANK'S

**Comment by Tigger2014** [comment]
Have you manually added the relevant routes to allow this, routes are not created by default.?

**Comment by jimmyparr** [comment]
> Have you manually added the relevant routes to allow this, routes are not created by default.?

NOPE CAN YOU BE MORE PRECISE ON HOW TO : THANK'S

**Comment by jimmyparr** [comment]
> Have you manually added the relevant routes to allow this, routes are not created by default.?

IPSEC DOES ROUTING BY ITSELF, OPENVPN DOES THE SAME, WIREGUARD IN PFSENSE 2.5  ALSO. WHAT HAPPENS IN THE NEW VERSION ?

**Comment by jimmyparr** [comment]
NOPE CAN YOU BE MORE PRECISE ON HOW TO : THANK'S

IPSEC DOES ROUTING BY ITSELF, OPENVPN DOES THE SAME, WIREGUARD IN PFSENSE 2.5 ALSO. WHAT HAPPENS IN THE NEW VERSION ?

**Comment by theonemcdonald** [comment]
Right now you either need to create static routes or use a dynamic routing protocol. This is something that we are still working on to improve.

**Comment by jimmyparr** [comment]
> Right now you either need to create static routes or use a dynamic routing protocol. This is something that we are still working on to improve.

THANK'S FOR TAKING TIME TO ANSWER ! I WILL WAIT FOR FIX. AS THE MENTION EXPERIMENTAL SAY'S I REPORTED THE ISSUE FOR AMELIRATIONS :) 
HAVE A NICE ONE

**Comment by jimmyparr** [comment]
> Right now you either need to create static routes or use a dynamic routing protocol. This is something that we are still working on to improve.

GENERALLY SPEAKING IF ALLOWED IP = WIREGUARD TUNNEL + SUBNET IP : MAYBE THE ROUTING CAN BE ADD USING THIS VARIABLE !

THIS IS JUST AN IDEA
YOLO

**Comment by Tigger2014** [comment]
This is already being worked on under #43 
Thanks
