### ISSUE TITLE
Firewall rules not working on assigned interface

### ISSUE THREAD

**Issue by ogmueller** [theonemcdonald/pfSense-pkg-WireGuard#143]
**Describe the bug**
I setup a tunnel using an assigned interface (called WG). When creating firewall rules on this interface "WG", they won't work. The only rules that apply are the ones on interface "WireGuard", which has been created by the wireguard package itself.
In order to test it, i just blocked different IPs on the two interfaces and tried to ping them through the tunnel.

**To Reproduce**
Create tunnel and assign interface (e.g. named "WG").
Create firewall rule on interface "WireGuard" e.g. blocking IP 192.168.1.4.
Create firewall rule on interface "Test" e.g. blocking IP 192.168.1.2.
Ping both IPs through the tunnel.
Currently 192.168.1.4 gets blocked, but 192.168.1.2 doesn't.
Btw. I can see that traffic is going through that interface "WG", once I start pinging.

**Expected behavior**
Because I have assigned this interface, I would assume, that the firewall rules a related and working on it.
I would have expected 192.168.1.2 to be blocked and not the other way round.

**Screenshots**
<img width="575" alt="Screenshot 2021-07-12 at 11 09 04" src="https://user-images.githubusercontent.com/788989/125261939-08ae1c00-e302-11eb-8e4c-7a3f3392c4ca.png">
<img width="706" alt="Screenshot 2021-07-12 at 11 08 32" src="https://user-images.githubusercontent.com/788989/125261946-0946b280-e302-11eb-9ab0-e64958470e3e.png">
<img width="701" alt="Screenshot 2021-07-12 at 11 08 25" src="https://user-images.githubusercontent.com/788989/125261948-09df4900-e302-11eb-8d18-8cf1e91fe21b.png">

**Version information (please complete the following information):**
 - PfSense: 2.5.2-RELEASE
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210606_1
 - pfSense-pkg-WireGuard: 0.1.3_1

**Comment by Tigger2014** [comment]
is 192.168.1.0/24 the VPN subnet?

are you trying to ping from another subnet on the firewall?

**Comment by ogmueller** [comment]
VPN subnet is 10.56.4.0/24.
Ping is from other location connected through WireGuard.

**Comment by Tigger2014** [comment]
Ah ok, so the 192.168.1.0/24 subnet is on another interface on the same firewall as 10.56.0.254?

**Comment by ogmueller** [comment]
Yes, that is correct. It is the "internal" network.

**Comment by Tigger2014** [comment]
This is caused by your allow any rule on the WireGuard tab.

**Comment by ogmueller** [comment]
But if wireguard is assigned to an interface, I assume, that firewall rules on that interface are working, right?
They are not, because on the assigned interface, the first rule should blocks 192.168.1.2. The second one is the allow any.
And it is the same on the "WireGuard" interface, where the first one blocks and the second allows any. There everything works.

**Comment by theonemcdonald** [comment]
This is expected. Re : https://docs.netgate.com/pfsense/en/latest/firewall/rule-methodology.html#rule-processing-order

**Comment by ogmueller** [comment]
Thanks for this explanation.

It would help, if the "WireGuard Interface Group" would add my assigned interface "WG" as a member, than it would have been clear, that WireGuard is still part of this interface group. I thought, that with the interface assignment, WireGuard is not part of any group anymore.
