### ISSUE TITLE
Bring up interfaces early during startup

### ISSUE THREAD

**Issue by theonemcdonald** [theonemcdonald/pfSense-pkg-WireGuard#2]
We need a mechanism to bring up interfaces early during startup. Because packages start after interfaces are configured, we need a way to bring up these interfaces early to avoid interface assignment issues.

Edit: The latest code now supports handling bringing up and tearing down interfaces using `/usr/local/etc/rc.d/wireguard [ start | stop | restart ]`. Entries are automatically added and removed from this file. In this way, an `earlyshellcmd` can be executed to build up wgX interfaces early at startup.

`<earlyshellcmd>service wireguard start</earlyshellcmd>`

**Comment by theonemcdonald** [comment]
I'm going to reopen this as work still needs to be done to actually get the `earlyshellcmd` installed during package installation. This is ongoing work.

**Comment by Tigger2014** [comment]
https://github.com/pfsense/FreeBSD-ports/blob/487258ae7cbd1039621b5dc5ac625f23d5519f39/sysutils/pfSense-pkg-Shellcmd/files/usr/local/pkg/shellcmd.inc
https://docs.netgate.com/pfsense/en/latest/development/boot-commands.html

Both of above may help with adding this functionality

**Comment by theonemcdonald** [comment]
We are closer
![configtunnels](https://user-images.githubusercontent.com/3102039/114317387-d4924780-9ad5-11eb-8249-82754ecaf1cd.png)

**Comment by theonemcdonald** [comment]
This is resolved. WireGuard tunnels are now built as early as they can.
