### ISSUE TITLE
Where to discuss?

### ISSUE THREAD

**Issue by vajonam** [theonemcdonald/pfSense-pkg-WireGuard#28]
I am running this now! Awesome works like a champ. Is there a place to talk about all the stuff happening? Slack / Discord / Reddit?

**Comment by vajonam** [comment]
Done. [invite](https://discord.gg/A68S9YWA)

**Comment by theonemcdonald** [comment]
https://discord.gg/VjmRExyQww !

**Comment by gonzopancho** [comment]
You're invited to discuss this on the [Netgate forum](forum.netgate.com).

**Comment by theonemcdonald** [comment]
@gonzopancho Sounds great!

**Comment by vajonam** [comment]
Create a thread in in the Forum https://forum.netgate.com/topic/163133/wireguard-lives
