### ISSUE TITLE
Option to encrypt keypairs in config.xml

### ISSUE THREAD

**Issue by theonemcdonald** [theonemcdonald/pfSense-pkg-WireGuard#3]
It would be nice to encrypt tunnel keypairs when stored in config.xml. With this option enabled, keypairs should be stored in a manner similar to [PowerShell SecureStrings](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertto-securestring?view=powershell-7.1). In this way, keypairs can only be decrypted on the installation (or hardware) that encrypted them.

**Comment by Tigger2014** [comment]
This might be undesired as PFSense backups are designed to be restored in the case of HW failure, if the encryption is device locked this breaks. Also if the encryption is not device locked this likely defeats the purpose of the encryption.

**Comment by theonemcdonald** [comment]
Good point
