### ISSUE TITLE
Certain packages that are bound to a wireguard interface fail to bind at bootup

### ISSUE THREAD

**Issue by vajonam** [theonemcdonald/pfSense-pkg-WireGuard#32]
Looks like unbound when asked to listen on the WG assigned interface doesn't do so because it starts up before wireguard. 

The work around is to use an LAN IP of the pfsense box as DNS on the wg client DNS settings. and ensure that tunnel can route to that IP using FW rules.  

Known affected:
- nginx (web ui)
- unbound
- avahi
- dnsmasq
- snmp
- ntp
- dyndns
- FRR
- dpinger

this is a start. I am only using `unbound` but I think `dnsmasq` will be another popular one

**Comment by theonemcdonald** [comment]
We might need to start curating a list of packages that need to restart after the wireguard package. We can make a new definition in `wg_globals.inc` with an array of services that need to be restarted after WireGuard comes up.

**Comment by theonemcdonald** [comment]
https://github.com/theonemcdonald/pfSense-pkg-WireGuard/releases/tag/v0.0.6_3

**Comment by vajonam** [comment]
wong bug :-) think you meant to close #33

**Comment by vajonam** [comment]
- unbound
- avahi
- dnsmasq
- snmp? 
- ntp
- dyndns

this is a start. I am only using `unbound` but I think `dnsmasq` will be another popular one

**Comment by theonemcdonald** [comment]
> wong bug :-) think you meant to close #33

Doh, you're right , reopened it

**Comment by Tigger2014** [comment]
partial fix in #47

**Comment by vajonam** [comment]
This will be fixed when latest code is merged in.

**Comment by theonemcdonald** [comment]
Fixed internally, new build coming soon
