### ISSUE TITLE
0.0.6_3 - seems to have input validation issue on "AllowedIPs"  field - leading white space is permitted and saved

### ISSUE THREAD

**Issue by mfld-pub** [theonemcdonald/pfSense-pkg-WireGuard#35]
Editing the peer, removing the leading white space that originated from a copy/paste issue and then clicking UPDATE followed by SAVE does not save the new value. The leading white space is still there. I can get rid of it by editing the value for instance by changing 172.16.71.2/32 to 172.16.71.3/32 and removing the white space. 

~~The presence of the white space seemed to break my functionality.~~

Edit: 
The presence of the leading white space seems cosmetic in nature. It does effect the way the `AllowedIPs =`  lines are written in the tun_wg*.conf

![dsfff](https://user-images.githubusercontent.com/66289900/115566155-33c93680-a2e4-11eb-933d-7de55f30548e.JPG)

**Comment by theonemcdonald** [comment]
This field is a crossover from the Netgate code. I am not currently using this underneath. It has usefulness for features we'd like to have, but right now it is just cosmetic.

**Comment by Tigger2014** [comment]
@theonemcdonald  Should the field be hidden for now if its not used for anything as it could be confusing?

**Comment by mfld-pub** [comment]
> 
> 
> This field is a crossover from the Netgate code. I am not currently using this underneath. It has usefulness for features we'd like to have, but right now it is just cosmetic.

I uploaded and worked from the wrong screenie. Updated original post now. 
Actual Issue is re: `AllowedIPs =` but cosmetic only. `PeerAddress =` seems indeed inert. 

![fdssf3](https://user-images.githubusercontent.com/66289900/115573738-39764a80-a2eb-11eb-9563-5c7e6dc399a3.JPG)

**Comment by theonemcdonald** [comment]
I'm going to close this and file it under cosmetic bug. Low priority and will likely get fixed organically as I continue to improve the UX.
