### ISSUE TITLE
Create firewall rule for peers automatically

### ISSUE THREAD

**Issue by Tigger2014** [theonemcdonald/pfSense-pkg-WireGuard#39]
Add an option to create firewall rules for peer if required.
The peer would need to have a static ip address for this to work and the endpoint specified in PfSense.
This should be possible to enable on a peer basic (individual IPs) or on a tunnel level (open port to any ip).
This should be user configurable.

**Comment by vajonam** [comment]
should this also include the addition of punching the hole in the WAN interface for the tunnel itself? or separate bug fo that?

**Comment by Tigger2014** [comment]
This should not be handled by the pkg but rather by the standard firewall rules to allow ip whitelisting etc.
