### ISSUE TITLE
Creating a secondary wg tunnel does not add the peer

### ISSUE THREAD

**Issue by fsamareanu** [theonemcdonald/pfSense-pkg-WireGuard#40]
**Describe the bug**
1. Create wireguard tunnel and corresponding peer. All ok.
2. Create secondary wireguard tunnel and corresponding peer. Tunnel gets created, peer does not.

**To Reproduce**
See above

**Expected behavior**
Secondary tunnel should be created and defined peer should be added.

**Screenshots**

![image](https://user-images.githubusercontent.com/38040820/115687594-dc5db180-a349-11eb-9787-660c88f4b380.png)

**Version information (please complete the following information):**
 - PfSense: 2.6
 - WireGuard-tools: wireguard-tools-1.0.20210315_4
 - WireGuard-kmod: wireguard-kmod-0.0.20210415
 - pfSense-pkg-WireGuard: pfSense-pkg-WireGuard-0.0.7

**Other information

XML contents, redacted:

                <wireguard>
                        <config>
                                <keep_conf>yes</keep_conf>
                                <hide_secrets></hide_secrets>
                        </config>
                        <tunnel>
                                <name>tun_wg0</name>
                                <mtu>1420</mtu>
                                <enabled>yes</enabled>
                                <descr><![CDATA[REDACTED]]></descr>
                                <interface>
                                        <address></address>
                                        <listenport>51820</listenport>
                                        <privatekey>REDACTED</privatekey>
                                        <publickey>REDACTED</publickey>
                                        <mtu>1400</mtu>
                                </interface>
                                <peers>
                                        <wgpeer>
                                                <publickey>REDACTED</publickey>
                                                <endpoint>REDACTED</endpoint>
                                                <allowedips>0.0.0.0/0</allowedips>
                                                <descr><![CDATA[REDACTED]]></descr>
                                                <persistentkeepalive>25</persistentkeepalive>
                                                <presharedkey></presharedkey>
                                                <port>REDACTED</port>
                                                <peerwgaddr></peerwgaddr>
                                        </wgpeer>
                                </peers>
                        </tunnel>
                        <tunnel>
                                <name>tun_wg1</name>
                                <mtu>1420</mtu>
                                <enabled>yes</enabled>
                                <descr><![CDATA[REDACTED]]></descr>
                                <interface>
                                        <address></address>
                                        <listenport>51821</listenport>
                                        <privatekey>REDACTED</privatekey>
                                        <publickey>REDACTED</publickey>
                                        <mtu>1500</mtu>
                                </interface>
                                <peers></peers>
                        </tunnel>
                </wireguard>

**Comment by theonemcdonald** [comment]
I suspect that the issue is the empty `<peers></peers>` 

Can you try https://github.com/theonemcdonald/pfSense-pkg-WireGuard/releases/tag/v0.0.7_1

**Comment by fsamareanu** [comment]
The new release fixes it. Thank you.

**Comment by theonemcdonald** [comment]
Thanks @fsamareanu for testing!
