### ISSUE TITLE
[BUG] Page permissions broken on LDAP admins

### ISSUE THREAD

**Issue by Tigger2014** [theonemcdonald/pfSense-pkg-WireGuard#41]
**Describe the bug**
page permissions broken on LDAP admins

**Screenshots**
![image](https://user-images.githubusercontent.com/2319079/115708842-6583e100-a368-11eb-9fd3-952a7f42db14.png)

**Version information (please complete the following information):**
- PfSense: 2.6.0
- pfSense-pkg-WireGuard    0.0.7_1 
- wireguard-kmod    0.0.20210415  
- wireguard-tools    1.0.20210315_4

**Comment by theonemcdonald** [comment]
This needs to be tested on 2.5.1 as well...though I suspect I need to do some more study of other packages and see how define page permissions. I thought I had this worked out

**Comment by theonemcdonald** [comment]
Just pushed a fix for this. Will make it into the next build
