### ISSUE TITLE
[BUG] Wireguard Interface Group Gets Reset

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#44]
When saving a change to a tunnel the Interface Group will get reset to empty.

I have 2 wg tunnels with defined interfaces and both members of the Wireguard Interface Group. Made a change to the description of one of the tunnels and saved the tunnel. This caused the Wireguard Interface Group to reset to no members.

Nice package, been running it for a week without any real issues!

**Comment by theonemcdonald** [comment]
Can you copy/paste the interface status block from Status page?

**Comment by theonemcdonald** [comment]
This is not a bug, it is a limitation with how packages can create interface groups. I have adjusted the description for more clarity.

You should not be editing this group, period.

**Comment by gshaffer1** [comment]
I've not used Interface Groups before, but when I saw it empty (i.e. Members was empty), I went ahead and added the wg interfaces. I looked at the status and "groups: wg WireGuard" exists. Adding a "do not edit" to the description would be helpful.

Thanks!

**Comment by theonemcdonald** [comment]
Will be in the next release!
