### ISSUE TITLE
[BUG] Default Gateway Switch

### ISSUE THREAD

**Issue by DrAg0n141** [theonemcdonald/pfSense-pkg-WireGuard#52]
I have a Multi WAN Setup and the Wireguard Switch not Back after Failover. It now uses my Secondary WAN.

**Version information (please complete the following information):**
 - PfSense: 2.5.1
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210424_1
 - pfSense-pkg-WireGuard: 0.0.8

Is your Pfsense default gateway set to a failover group? Yes it is.
Do you have keep alive enabled in the tunnel? Yes with 25 seconds.
does this tunnel get initiated by the pfsense end or the other end? By the pfSense with the Multi Wan Setup, the other End is set to dynamic.

**Comment by theonemcdonald** [comment]
Are you clearing gateway states on wan failover?

**Comment by DrAg0n141** [comment]
Yes i have State Killing on Gateway Failure enabled.

**Comment by Tigger2014** [comment]
Is your Pfsense default gateway set to a failover group?
Do you have keep alive enabled in the tunnel?
does this tunnel get initiated by the pfsense end or the other end?

It could be possible that if the traffic is coming from the other end via WAN 2 that wireguard is returning over the same interface, @theonemcdonald does this sound possible from the kmod side?

**Comment by theonemcdonald** [comment]
> Please can you fill in the issue template data, especially your versions, I have added them to the end of your initial post?
> 
> Is your Pfsense default gateway set to a failover group?
> Do you have keep alive enabled in the tunnel?
> does this tunnel get initiated by the pfsense end or the other end?
> 
> It could be possible that if the traffic is coming from the other end via WAN 2 that wireguard is returning over the same interface, @theonemcdonald does this sound possible from the kmod side?

This sounds plausible, will need to test this more.

**Comment by theonemcdonald** [comment]
I'm going to close this for now. We haven't heard any new reports of this issue and too much has changed with both the package code and kernel code since it was opened originally.
