### ISSUE TITLE
Constant Wireguard upgrade error message

### ISSUE THREAD

**Issue by Zackptg5** [theonemcdonald/pfSense-pkg-WireGuard#58]
Every time pfsense checks for updates, I get this message: `ERROR: There are WireGuard tunnels enabled on your config. Please remove or disable them before upgrade. @ 2021-05-01 02:18:46`
I'm on v2.5.1. Is there any way to disable this message? If so, it'd be a handy thing to have in the readme

**Comment by fsamareanu** [comment]
This message isn’t generated by the wire guard package. The check and the error message are in netgate’s scripts.

**Comment by Zackptg5** [comment]
That's what I was assuming. What I attempted to ask is if there's a way for us to patch/disable that message in our pfsense install and if so, can that be added to the readme?

**Comment by fsamareanu** [comment]
Not 100% sure but it seems this one might be the reason you're getting the message: https://redmine.pfsense.org/issues/11808

**Comment by Tigger2014** [comment]
This is not a bug/issue and a fix has already been pushed upstream but is not yet in 2.5.1.

I have included the steps below to stop this


From `/usr/local/libexec/pfSense-upgrade`
Remove the section that is like below to stop the errors appearing
```
	if sed -e '/<wireguard>/,/<\/wireguard>/!d' \
	    /cf/conf/config.xml | grep -q '<enabled>yes'; then
		notice "ERROR: There are WireGuard tunnels enabled" \
		    "on your config.  Please remove or disable them" \
		    "before upgrade."
		_echo "ERROR: There are WireGuard tunnels enabled" \
		    "on your config.  Please remove or disable them" \
		    "before upgrade."
		_exit 1
	fi
```
