### ISSUE TITLE
Include wireguard module and tools in package

### ISSUE THREAD

**Issue by Tigger2014** [theonemcdonald/pfSense-pkg-WireGuard#6]
Hi, 

Great start on the porting. I thought it might be good at add this to the list of potentially needed things for this.

Let me know your thoughts

**Comment by theonemcdonald** [comment]
Based on what is done with other packages that depend on other packages (e.g. FRR, Avahi, etc.), it seems that the trend is to keep the pfSense specific bits in the `pfSense-pkg-...` package and then build dependencies as-is...less for us to maintain.

**Comment by Tigger2014** [comment]
Ah agreed, i had missed that when i went looking.
