### ISSUE TITLE
NAT

### ISSUE THREAD

**Issue by CobbyJ** [theonemcdonald/pfSense-pkg-WireGuard#65]
I have my Wireguard connected but i cant seem to get NAT working so all traffic goes via Wireguard. any examples?

Also it doesnt have a Gateway so i am unable to go between Wireguard and normal Network.

**Comment by theonemcdonald** [comment]
Assign the tunnel to a pfSense interface and create a gateway entry just as you would do if you were configuring a WAN. Then you can NAT and policy route using that gateway.
