### ISSUE TITLE
[BUG] Show default port when not specified

### ISSUE THREAD

**Issue by Tigger2014** [theonemcdonald/pfSense-pkg-WireGuard#67]
**Describe the bug**
Default port is not shown on the peer page (vpn_wg_peers.php)
Additionally as discussed this should actually be saved as the default port into the config rather than a cosmetic UI change

**Screenshots**
![image](https://user-images.githubusercontent.com/2319079/117551035-8708ec00-b03b-11eb-8b2c-4b305126c58f.png)

**Version information (please complete the following information):**
 - pfSense-pkg-WireGuard:DEVEL 0.0.9

**Comment by theonemcdonald** [comment]
Fixed
