### ISSUE TITLE
Peer address

### ISSUE THREAD

**Issue by andrewluebke** [theonemcdonald/pfSense-pkg-WireGuard#74]
Am I missing something where you set the Peer Wireguard Address?
This part in the old system:

![2021-05-11 20_00_48-pfSense customccc com - VPN_ WireGuard_ Tunnel — Mozilla Firefox](https://user-images.githubusercontent.com/45699172/117912048-a306ca80-b293-11eb-8701-85ecd2450f2a.png)

**Comment by theonemcdonald** [comment]
There is currently no part of this implementation that necessitates knowing the address of the peer itself.

**Comment by theonemcdonald** [comment]
Closing this. We will make an announcement when peer address configuration has a use-case here (think peer exporting, etc.)
