### ISSUE TITLE
tun_wg0 does not work with DHCPv6

### ISSUE THREAD

**Issue by dersch81** [theonemcdonald/pfSense-pkg-WireGuard#79]
It is not possible to let a DHCPv6 service work on the tun_wg interface to push PD to some peer. 

`/services_dhcpv6.php: The command '/usr/local/sbin/dhcpd -6 -user dhcpd -group _dhcp -chroot /var/dhcpd -cf /etc/dhcpdv6.conf -pf /var/run/dhcpdv6.pid em1.172 tun_wg0' returned exit code '1', the output was 'Internet Systems Consortium DHCP Server 4.4.2 Copyright 2004-2020 Internet Systems Consortium. All rights reserved. For info, please visit https://www.isc.org/software/dhcp/ Config file: /etc/dhcpdv6.conf Database file: /var/db/dhcpd6.leases PID file: /var/run/dhcpdv6.pid Wrote 5 NA, 0 TA, 5 PD leases to lease file. **Bound to *:547 Unsupported device type 23 for "tun_wg0"** If you think you have received this message due to a bug rather than a configuration issue please read the section on submitting bugs on either our web page at www.isc.org or in the README file before submitting a bug. These pages explain the proper process and the information we find helpful for debugging. exiting.'`

**Comment by theonemcdonald** [comment]
This isn't something we can fix on our end.

**Comment by dersch81** [comment]
Unsupported device type 23 for "tun_wg0" - what does it mean device type 23? And where can it be fixed? It is a netgate bug or something else? Normally it is fine to run dhcpv6 service on wg interfaces.

**Comment by theonemcdonald** [comment]
Are you positive that this worked on 2.5.0? from what I can tell, iscdhcp is failing because it doesn't see a MAC address on the interface...wg interfaces are L3 so they don't have mac addresses.

**Comment by dersch81** [comment]
No, i never tried with 2.5.0 i did it already with OpenWRT or just on some debian. Ok i did not see this regarding the MAC. So it has nothing to do with your package. It is an issue with iscdhcp on pfsense. Many thanks
