### ISSUE TITLE
Ports repo & steps

### ISSUE THREAD

**Issue by Tigger2014** [theonemcdonald/pfSense-pkg-WireGuard#8]
This is a WIP post of info regarding running our own ports repo and the steps needed

Needed:

- internet facing server for the package repo and testing, Server must be running freeBSD
- Ideally webhook functionality to rebuild module on ports server from github when version is bumped.

**Comment by Tigger2014** [comment]
https://github.com/j-white/minion-on-pfsense/blob/master/BUILDING.md - Used loosely to setup ports server
https://github.com/marcelloc/Unofficial-pfSense-packages/blob/master/25_unofficial_packages_list.patch - modify pfsense to show the packages in the GUI

/usr/local/etc/pkg/repos/pfSense.conf
ADD 
pfSense-WG: {
  url: "http://*************:8080/packages/freebsd_12-2x64-devel",
  mirror_type: "http",
  signature_type: none,
  fingerprints: none,
  enabled: yes
}

**Comment by Tigger2014** [comment]
![image](https://user-images.githubusercontent.com/2319079/114270896-bdd0ef80-9a06-11eb-8801-ca447311f82d.png)

**Comment by Tigger2014** [comment]
## Overview

These instructions will guide you in setting up a [Poudriere](https://www.freebsd.org/doc/handbook/ports-poudriere.html) repository to build and host a port tree with custom pfSense packages.

## Requirements

* An instance of FreeBSD 12.5-RELEASE x64

### Droplet setup

To upgrade a droplet running an earlier version of FreeBSD, you can use:

```sh
sudo freebsd-update -r 12.5-RELEASE upgrade
sudo freebsd-update install
sudo reboot
sudo freebsd-update install
sudo reboot
```

Also, if you're using a droplet with less than 4G of RAM, you'll likely want to add a [swap file](https://www.freebsd.org/doc/handbook/adding-swap-space.html).

## Poudriere Setup

> These instruction are based [How To Set Up a Poudriere Build System to Create Packages for your FreeBSD Servers](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-poudriere-build-system-to-create-packages-for-your-freebsd-servers)

### Install Poudriere and Nginx

```sh
sudo pkg install poudriere nginx screen git dialog4ports
```

### Create an SSL Certificate and Key

```sh
sudo mkdir -p /usr/local/etc/ssl/{keys,certs}
sudo chmod 0600 /usr/local/etc/ssl/keys
sudo openssl genrsa -out /usr/local/etc/ssl/keys/poudriere.key 4096
sudo openssl rsa -in /usr/local/etc/ssl/keys/poudriere.key -pubout -out /usr/local/etc/ssl/certs/poudriere.cert
```

### Configure Poudriere

Edit `/usr/local/etc/poudriere.conf` and make sure the following properties are set:

```sh
NO_ZFS=yes
FREEBSD_HOST=ftp://ftp.freebsd.org
POUDRIERE_DATA=${BASEFS}/data
CHECK_CHANGED_OPTIONS=verbose
CHECK_CHANGED_DEPS=yes
PKG_REPO_SIGNING_KEY=/usr/local/etc/ssl/keys/poudriere.key
URL_BASE=http://server_domain_or_IP
GIT_URL=https://github.com/Tigger2014/FreeBSD-ports
```

### Configure Nginx

```sh
sudo sh -c "echo 'nginx_enable="YES"' >> /etc/rc.conf"
```

Update `/usr/local/etc/nginx/nginx.conf` with:
```
server {
    listen 80 default;
    server_name server_domain_or_IP;
    root /usr/local/share/poudriere/html;

    location /data {
        alias /usr/local/poudriere/data/logs/bulk;
        autoindex on;
    }

    location /packages {
        root /usr/local/poudriere/data;
        autoindex on;
    }
}
```

Add `log` to the `text/plain` mime type in `/usr/local/etc/nginx/mime.types`:
```
text/plain                          txt log;
```

Start nginx:
```sh
sudo service nginx start
```

### Create the jail

```sh
sudo poudriere jail -c -j freebsd_12-5x64 -v devel
```
### Create the ports tree

```sh
sudo poudriere ports -v -c -m git -B devel -p devel
```

### Configure the ports

Create the list of packages to compile:
```
sudo sh -c "echo 'net/pfSense-pkg-WireGuard' >> /usr/local/etc/poudriere.d/pfSense-minion-packages-list"
```

Set some global options:
```
sudo sh -c "echo 'OPTIONS_UNSET+= DOCS NLS X11 EXAMPLES' >> /usr/local/etc/poudriere.d/freebsd_12-5x64-make.conf"
```

Configure the port options:

```sh
sudo mkdir /usr/local/etc/poudriere.d/freebsd_12-5x64-options
sudo poudriere options -j freebsd_12-5x64 -p devel -f /usr/local/etc/poudriere.d/pfSense-minion-packages-list
```

### Build (or rebuild) the ports

```sh
sudo poudriere jail -u -j freebsd_12-5x64
sudo poudriere ports -u -p devel
screen
sudo mkdir -p /usr/ports/distfiles
sudo poudriere bulk -j freebsd_12-5x64 -p devel-f /usr/local/etc/poudriere.d/pfSense-minion-packages-list
```

**Comment by theonemcdonald** [comment]
This is good stuff, thanks Ben!

**Comment by Tigger2014** [comment]
To enable GUI upgrades
 
Remove 
/usr/local/libexec/pfSense-upgrade
# Do not upgrade if there are enabled WireGuard tunnels on config
		if sed -e '/<wireguard>/,/<\/wireguard>/!d' \
		    /cf/conf/config.xml | grep -q '<enabled>yes'; then
			notice "ERROR: There are WireGuard tunnels enabled" \
			    "on your config.  Please remove or disable them" \
			    "before upgrade."
			_echo "ERROR: There are WireGuard tunnels enabled" \
			    "on your config.  Please remove or disable them" \
			    "before upgrade."
			_exit 1
		fi

**Comment by theonemcdonald** [comment]
Also worth noting that this package will NOT read tunnel configurations made via 2.5.0 as the config.xml paths have changed.

I might build this ability in, but this is a low priority...just recreate your tunnels as necessary.

**Comment by Tigger2014** [comment]
> Also worth noting that this package will NOT read tunnel configurations made via 2.5.0 as the config.xml paths have changed.
> 
> I might build this ability in, but this is a low priority...just recreate your tunnels as necessary.

I think reading them is pointless, The pfsense upgrader will block an upgrade anyway, we would need to detect WG auto install the new version and restore the config. Given this is alpha i think its best to not

**Comment by theonemcdonald** [comment]
> To enable GUI upgrades
> 
> Remove
> /usr/local/libexec/pfSense-upgrade
> 
> # Do not upgrade if there are enabled WireGuard tunnels on config
> ```
> 	if sed -e '/<wireguard>/,/<\/wireguard>/!d' \
> 	    /cf/conf/config.xml | grep -q '<enabled>yes'; then
> 		notice "ERROR: There are WireGuard tunnels enabled" \
> 		    "on your config.  Please remove or disable them" \
> 		    "before upgrade."
> 		_echo "ERROR: There are WireGuard tunnels enabled" \
> 		    "on your config.  Please remove or disable them" \
> 		    "before upgrade."
> 		_exit 1
> 	fi
> ```

Putting this here for a reminder: https://github.com/pfsense/FreeBSD-ports/blob/RELENG_2_5_1/sysutils/pfSense-upgrade/files/pfSense-upgrade#L638

The pfSense-upgrade package that is available on the 2.5.1 repository is currently NOT tracking Netgate's internal development. The current WireGuard check that is shipping in the 2.5.1 repository is no longer upgrade blocking as per:

```
if sed -e '/<wireguard>/,/<\/wireguard>/!d' \
	  /cf/conf/config.xml | grep -q '<enabled>yes'; then
		  notice "ERROR: There are WireGuard tunnels enabled" \
		  "on your config.  Please remove or disable them" \
		  "before upgrade."
fi
```

**Comment by theonemcdonald** [comment]
https://redmine.pfsense.org/issues/11808#change-53025

This is being addressed upstream!

**Comment by netstx** [comment]
Looks like it's targeted for 2.6.0 :(

**Comment by theonemcdonald** [comment]
Check again! 😁

**Comment by Tigger2014** [comment]
Now PfSense will be building the kmod and tools I think we should look again to creating a ports repo to host this package until its merged, as its likely to have a lot of fine tuning over the next few releases, This would be a simple pkg install command instead of needing to download the files.

Or a system patch which i can provide and all install could be done via gui

I think we can set this up on a small vps.

**Comment by vajonam** [comment]
We will need the following patch to be applied

https://github.com/marcelloc/Unofficial-pfSense-packages/blob/master/25_unofficial_packages_list.patch

and `/usr/local/etc/pkg/repos`
```
FreeBSD: { enabled: no }

Unofficial: { url: "pkg+https://packages.mced.tech/packages/freebsd_12-2x64-devel",
            mirror_type: "srv",
            enabled: yes}
```
