### ISSUE TITLE
[BUG] Crash after Peers save

### ISSUE THREAD

**Issue by juliokele** [theonemcdonald/pfSense-pkg-WireGuard#81]
Crash after Peers save (pfsense 2.6.0-DEVELOPMENT, wireguard package 0.0.9):
```
Crash report begins.  Anonymous machine information:

amd64
12.2-STABLE
FreeBSD 12.2-STABLE devel-12-n226624-e22beee72a6a pfSense

Crash report details:

PHP Errors:
[13-May-2021 14:08:30 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/pkg/wireguard/wg_validate.inc on line 149



No FreeBSD crash data found.
```

![tunnel](https://user-images.githubusercontent.com/8851893/118124821-6b646380-b3f6-11eb-99dd-fef4e472f794.png)
![peer](https://user-images.githubusercontent.com/8851893/118124835-6ef7ea80-b3f6-11eb-9bdb-cd3ab37839cc.png)
![status](https://user-images.githubusercontent.com/8851893/118125227-fe9d9900-b3f6-11eb-95ba-da26f4d9ee5e.png)

**Comment by vajonam** [comment]
Quite sure this already fixed.

**Comment by juliokele** [comment]
Yes, i see now:
https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/3a2338a4c0c24167bcebb92e35ec9cd61127de22/src/files/usr/local/pkg/wireguard/wg_validate.inc#L149
