### ISSUE TITLE
Pre-Shared key generated by pfSense peer config rejected by openWRT client

### ISSUE THREAD

**Issue by tcquade** [theonemcdonald/pfSense-pkg-WireGuard#85]
Key generated by pfSense VPN > WireGuard > Peers > Edit is rejected as invalid by openWRT Wireguard client.

An arbitrary base64 encoded key created within new pfSense Wireguard server is accepted by openWRT Wireguard client and pfSence Wireguard peer.

I'm guessing that the key generated by pfSence peer is not base64 encoded.

pfSense 2.6.0 Develpment, Wireguard 0.1.1_1

Ted

**Comment by theonemcdonald** [comment]
We produce keys using `wg(8)`, nothing special here. Can you generate a problematic keypair and post it?

**Comment by theonemcdonald** [comment]
Not a problem! Thanks for testing!
