### ISSUE TITLE
[BUG] PHP Errors

### ISSUE THREAD

**Issue by hjaltioj** [theonemcdonald/pfSense-pkg-WireGuard#86]
**Describe the bug**
Im no php or wireguard expert so bear with me :)

But i get a error on dashboard that says: pfSense has detected a crash report or programming bug. Click here for more information.

And in the error message is this message:

Crash report begins.  Anonymous machine information:

amd64
12.2-STABLE
FreeBSD 12.2-STABLE devel-12-n226630-46ad3b77c49b pfSense

Crash report details:

PHP Errors:
[21-May-2021 14:58:38 Europe/Copenhagen] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/www/wg/vpn_wg_peers_edit.php on line 259

No FreeBSD crash data found.

Line 259 is this:
foreach ($allowedips as $index => $ip) {

	list($address, $address_subnet) = explode("/", $ip);

	$group = new Form_Group(null);

	$group->addClass('repeatable');

	$group->add(new Form_IpAddress(
		"address{$index}",
		'Allowed IPs',
		$address,
		'BOTH'
	))->addMask("address_subnet{$index}", $address_subnet, 128, 1)
		->setWidth(5);

	$group->add(new Form_Button(
		"deleterow{$index}",
		'Delete',
		null,
		'fa-trash'
	))->addClass('btn-warning btn-sm');

	$section->add($group);

}

$section->addInput(new Form_Button(
	'addrow',
	'Add Allowed IP',
	null,
	'fa-plus'
))->addClass('btn-success btn-sm addbtn');

$form->add($section);

$form->addGlobal(new Form_Input(
	'act',
	'',
	'hidden',
	'save'
));

print($form);

?>

**Version information (please complete the following information):**
 - PfSense: Latest Develop version
 - WireGuard-tools: latest from package manager
 - WireGuard-kmod: latest from package manager
 - pfSense-pkg-WireGuard: latest from package manager

**Additional context**

VPN works, but this message comes all the time?? sorry for the inconvenience :) hope someone can help.
Have a good day.

**Comment by theonemcdonald** [comment]
This is fixed in our standalone builds, Netgate has a PR in review that includes the fix for this

**Comment by hjaltioj** [comment]
okey thanks :) sorry for the inconvenience

have a great day.

**Comment by theonemcdonald** [comment]
No inconvenience at all :)

Thanks
