### ISSUE TITLE
[PHP Warning] Use of undefined constant wg_

### ISSUE THREAD

**Issue by LeFouineur** [theonemcdonald/pfSense-pkg-WireGuard#87]
**Describe the bug**
Usage of a possible constant in code or leftover code in src/files/usr/local/www/wg/status_wireguard.php#L86

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/ef7b4b1f5d1f6ebf9ac82a1a2f5035b4923e1745/net/pfSense-pkg-WireGuard/files/usr/local/www/wg/status_wireguard.php#L84-L90

**To Reproduce**
Load the page _PFSENSE_/wg/status_wireguard.php

**Expected behavior**
Not having a PHP warning :)

**Screenshots**
![image](https://user-images.githubusercontent.com/274920/119220555-6042bf00-baeb-11eb-941f-28d2d85fcbd5.png)

**Version information (please complete the following information):**
 - PfSense: 2.6.0-DEVELOPMENT (amd64) built on Sat May 22 01:04:36 EDT 2021 
 - FreeBSD 12.2-STABLE devel-12-n226634-bdf0424cb2b5
 - WireGuard-tools**-lite**: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.1

**Additional context**
What is the usage of that constant here ?

Btw, thanks for your work on this implementation of Wireguard !!

**Comment by theonemcdonald** [comment]
Thanks, this was an oversight from some refactoring I'm sure. Fixed.
