### ISSUE TITLE
MTU/MSS Clamp Testing

### ISSUE THREAD

**Issue by theonemcdonald** [theonemcdonald/pfSense-pkg-WireGuard#9]
We need to test MTU and MSS clamping here. There was an issue in the original implementation with TCP that required clamping MSS at 1380 for v4 and 1360 for v6. This is not a problem for assigned interfaces as filter.inc correctly configures the MTU and MSS (via pf scrub max-mss).

But this is likely problematic for unassigned interfaces filtered using the Wireguard interface group. Should we remove the per tunnel MTU setting for unassigned tunnels and move this setting to a new wireguard settings tab? In that way we can apply scrub on the Wireguard interface group which would cover all unassigned interfaces collectively

**Comment by Tigger2014** [comment]
I wonder if we have the option to move the MTU setting from wireguard tabs onto the interfaces directly, and by default set it to 1380 on unassigned interfaces like you suggest.

Ideally i think this should be an interface setting rather than a wireguard one if possible

**Comment by theonemcdonald** [comment]
This might be resolved because of updated kmod code. Closing. Will reopen if necessary
