### ISSUE TITLE
[BUG] Policy-based routing for site-to-site WG tunnel not working

### ISSUE THREAD

**Issue by kevindd992002** [theonemcdonald/pfSense-pkg-WireGuard#90]
**Describe the bug**
I've had this PBR issue since WG in pfsense 2.5.0. This was my thread about it:

https://redmine.pfsense.org/issues/11679

My issues now are similar but not exactly the same. Basically, I have two sites that are connected via WG using your package in pfsense 2.5.1 boxes on both ends. Site A has a public IP and act as entry point for servers located in both Site A and Site B. Intersite traffic (client to client) works without issues. My issues are these:

1. I have a port forward in Site A to forward traffic to a client in Site B. This works fine when I setup an outbound NAT to translate the source IP to WG interface IP for this type of traffic so that return traffic from Site B won't use the default route and go back the same route (symmetric routing). This outbound NAT rule should not be necessary because if you use FW rules in the interface tab of the WG interface while keeping the WireGuard "group" tab ruleset empty, it should respect the reply-to's.

2. From Site B, I set PBR to route traffic from a certain source IP to use a gateway pointing to Site A's WG interface IP. In Site A, I set an outbound NAT rule in the WAN interface to translate traffic from the Site B subnet to the WAN address interface IP (for Internet access). I did a packet capture on the Site B WG interface and saw the packets reaching that interface so that means that the packets are being routed correctly. However, when I do a packet capture on the remote end's WG interface with the same source IP, I don't see any results. It's as if these packets are being encapsulated and coming out of Site B's WAN interface.

At this point, I really don't know if this is a pfsense bug or a WG bug but I would appreciate it if you can point me in the right direction. Also, this is really reproducible so let me know if you need some tests from my end to get to the bottom of this.

**Version information (please complete the following information):**
 - PfSense: 2.5.1
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.2

**Comment by kevindd992002** [comment]
I solved number 2. I didn't realize that WG allowed IP's also acted as a firewall for destination IP's for outbound. So if you want to route destination=Internet through the tunnel, you would have to add 0.0.0.0/0 to the allowed IP's on Site B. 

WG reference: https://www.wireguard.com/#conceptual-overview

**Comment by theonemcdonald** [comment]
Not sure this is a WireGuard issue tbh. Because there has been quite a bit of churn between 2.5.0/1 and 2.6.0 (and now 2.5.2), we need more testing before I can really investigate this as it might already be solved.

**Comment by kevindd992002** [comment]
Ok. I can't upgrade to the experimental 2.6.0 now so I won't be able to test but no-reply's worked "partially" in 2.5.0. They worked perfectly with openvpn s2s connections though. The workaround to this issue is SNAT (so that the return traffic gets directed to the WG interface IP) but I just don't want to SNAT unnecessarily. When you say "more testing", do you need the same tests performed on 2.5.2/2.6.0?

**Comment by theonemcdonald** [comment]
> When you say "more testing", do you need the same tests performed on 2.5.2/2.6.0?

Yes

**Comment by kevindd992002** [comment]
Ok. Question though. I know you said in one of your videos that it "seems" that the MTU/MSS issue with WG has been fixed and there's no need to modify it to 1420. I see in the Status tab that it is indeed set to 1500. However, when you assign the WG tunnel to an interface, do I still need to set it to MTU and MSS to 1420?

I'm trying to test the tunnel transfer speed between the two sites (200Mbps link in between) but I'm getting all sorts of bandwidth issues. It starts at 80Mbps and drops down erratically to less than 10Mbps. Copying a large file from the remote site has also very inconsistent speeds. With WG in 2.5.0, I did get consistent and full speeds when I do the same test. Not sure if this has to do something with the MTU/MSS issue.

**Comment by zx2c4** [comment]
Sounds like your first issue might be https://github.com/theonemcdonald/pfSense-pkg-WireGuard/issues/43 ?

**Comment by kevindd992002** [comment]
> 
> 
> Sounds like your first issue might be #43 ?

Ohh hey Jason. No, that's not it. I have static routes properly setup. Are you familiar with reply-to's in pfsense? Basically, for my first issue the packets that arrive the target server on Site B has an a public IP address. The return traffic from the Site B client then forwards the packet to the default route which is, of course, not the tunnel. If reply-to's are respected and working, the return traffic will route back to the VPN tunnel (where the forward traffic came from in the first place) even though the destination IP is an external IP. 

Reference:

https://docs.netgate.com/pfsense/en/latest/config/advanced-firewall-nat.html#disable-reply-to

**Comment by zx2c4** [comment]
Oh, thanks for the reference. That's interesting. This is pf's `reply-to` option. I'm not sure I totally understand how this works yet, but assuming pfSense is setting up the rules properly, I worry about things if it's working on other interfaces but not wireguard interfaces. The kernel module is always using `IP_SENDSRCADDR`/`IPV6_PKTINFO` when sending packets. I wonder if this is overriding your usage of `reply-to`?

I wonder if patching the module like this would fix the issue for you?

```diff
diff --git a/src/if_wg.c b/src/if_wg.c
index 037b039..1bb51bc 100644
--- a/src/if_wg.c
+++ b/src/if_wg.c
@@ -886,13 +886,13 @@ wg_send(struct wg_softc *sc, struct wg_endpoint *e, struct mbuf *m)
 
 	/* Get local control address before locking */
 	if (e->e_remote.r_sa.sa_family == AF_INET) {
-		if (e->e_local.l_in.s_addr != INADDR_ANY)
+		if (false && e->e_local.l_in.s_addr != INADDR_ANY)
 			control = sbcreatecontrol((caddr_t)&e->e_local.l_in,
 			    sizeof(struct in_addr), IP_SENDSRCADDR,
 			    IPPROTO_IP);
 #ifdef INET6
 	} else if (e->e_remote.r_sa.sa_family == AF_INET6) {
-		if (!IN6_IS_ADDR_UNSPECIFIED(&e->e_local.l_in6))
+		if (false && !IN6_IS_ADDR_UNSPECIFIED(&e->e_local.l_in6))
 			control = sbcreatecontrol((caddr_t)&e->e_local.l_pktinfo6,
 			    sizeof(struct in6_pktinfo), IPV6_PKTINFO,
 			    IPPROTO_IPV6);
```

**Comment by kevindd992002** [comment]
> 
> 
> Oh, thanks for the reference. That's interesting. This is pf's `reply-to` option. I'm not sure I totally understand how this works yet, but assuming pfSense is setting up the rules properly, I worry about things if it's working on other interfaces but not wireguard interfaces. The kernel module is always using `IP_SENDSRCADDR`/`IPV6_PKTINFO` when sending packets. I wonder if this is overriding your usage of `reply-to`?
> 
> I wonder if patching the module like this would fix the issue for you?
> 
> ```diff
> diff --git a/src/if_wg.c b/src/if_wg.c
> index 037b039..1bb51bc 100644
> --- a/src/if_wg.c
> +++ b/src/if_wg.c
> @@ -886,13 +886,13 @@ wg_send(struct wg_softc *sc, struct wg_endpoint *e, struct mbuf *m)
>  
>  	/* Get local control address before locking */
>  	if (e->e_remote.r_sa.sa_family == AF_INET) {
> -		if (e->e_local.l_in.s_addr != INADDR_ANY)
> +		if (false && e->e_local.l_in.s_addr != INADDR_ANY)
>  			control = sbcreatecontrol((caddr_t)&e->e_local.l_in,
>  			    sizeof(struct in_addr), IP_SENDSRCADDR,
>  			    IPPROTO_IP);
>  #ifdef INET6
>  	} else if (e->e_remote.r_sa.sa_family == AF_INET6) {
> -		if (!IN6_IS_ADDR_UNSPECIFIED(&e->e_local.l_in6))
> +		if (false && !IN6_IS_ADDR_UNSPECIFIED(&e->e_local.l_in6))
>  			control = sbcreatecontrol((caddr_t)&e->e_local.l_pktinfo6,
>  			    sizeof(struct in6_pktinfo), IPV6_PKTINFO,
>  			    IPPROTO_IPV6);
> ```

It definitely works with OpenVPN interfaces, yes. The only thing requirement for this to work is to use the tunnel interface rules tabs and not the tunnel "group" tabs. 

Sorry, I'm not a programmer myself so I don't know how to patch the module based on this. I'd be more than willing to try though if I have some kind of guide to do it.

**Comment by artooro** [comment]
It looks like I'm affected by this issue as well. On the original WireGuard in pfSense 2.5.0 this was working.
But in the latest version of this package on pfSense 2.5.2 the packets are getting from the other site over to the pfSense site, but not getting back. The firewall rules show the packets getting accepted, and a packet capture shows re-transmissions from the other site.
I've tried assigning the wireguard tunnel to a pfSense interface which doesn't seem to make a difference.

**Comment by zx2c4** [comment]
If you can confirm whether the patch above mitigates the issue, I can investigate root causes and real fixes.

**Comment by zx2c4** [comment]
Alternatively I can test and debug stuff if you can concoct a simple shell script that only makes use of wg, ifconfig, and pf (i.e. wireguard-tools + base).

**Comment by artooro** [comment]
I just found a way to make it work.

1. Assign the wireguard tunnel to a pfSense interface, and under 'IPv6 Upstream gateway" set the IP to the router on the other side of the tunnel.
2. Add a static route to route your "AllowedIPs" network over that gateway.

In my case this added a route to the system of:
`2001:470:xxx:xx::/64 2001:470:xxxx:x::1 UGS     tun_wg0`

And now traffic is flowing correctly.

@zx2c4 I'll try to come up with a script to reproduce for testing. In my case I have linux on one side with a few subnets and pfsense on the other side with a single IP.

**Comment by vajonam** [comment]
at the moment the package doesn't create any routes. setting an upstream gateway or monitor IP creates a route under the covers.  you will need static routes or policy based routes between your sites as of now.

**Comment by theonemcdonald** [comment]
Seems like this case is one where route management would be helpful.

In case there is more we need to look into, I've attached an archive with @zx2c4's patch 



[if_wg-debug90.tar.gz](https://github.com/theonemcdonald/pfSense-pkg-WireGuard/files/6618219/if_wg-debug90.tar.gz)

**Comment by kevindd992002** [comment]
Why am I not seeing a /boot/if_wg.ko on my existing pfsense system?

![image](https://user-images.githubusercontent.com/3907957/122966881-6fec4680-d3bc-11eb-95e1-7f1cc44ca130.png)

**Comment by kevindd992002** [comment]
> 
> 
> Seems like this case is one where route management would certainly be helpful.
> 
> In case there is more we need to look into, I've attached an archive with @zx2c4's patch. You'll need to backup and replace `/boot/if_wg.ko` and restart the package service (which will take care of tearing down and rebuilding tunnels using the patched module).
> 
> [if_wg-debug90.tar.gz](https://github.com/theonemcdonald/pfSense-pkg-WireGuard/files/6618219/if_wg-debug90.tar.gz)

Why am I not seeing a /boot/if_wg.ko on my existing pfsense system?

![image](https://user-images.githubusercontent.com/3907957/122966881-6fec4680-d3bc-11eb-95e1-7f1cc44ca130.png)

I see an if_wg.ko in these paths instead:

/boot/kernel.old/if_wg.ko
/boot/modules/if_wg.ko

Which one should I backup and replace?

**Comment by theonemcdonald** [comment]
Whoops, sorry it should be ```/boot/modules/if_wg.ko```

**Comment by kevindd992002** [comment]
@zx2c4, I tried using the patched module on both pfsense boxes on each side of the tunnel and restarted the package services. To test `reply-to`, I removed the outbound NAT I have on Site A to translate the sourceIP when the packets are destined to the client in Site B. It still did not work.

**Comment by kevindd992002** [comment]
@theonemcdonald Whil waiting for Jason's reply, will I experience anything bad if I keep using the patched module for the meantime?

**Comment by kevindd992002** [comment]
> 
> 
> @zx2c4, I tried using the patched module on the pfsense boxes on both sides of the tunnel and restarted the package services. To test `reply-to`, I removed the outbound NAT I have on Site A to translate the sourceIP when the packets are destined to the client in Site B. It still did not work.

@zx2c4 , just wondering if you've seen my reply regarding the testing results?

**Comment by Tigger2014** [comment]
@kevindd992002 Ive just tried to test out your issue from your first post. (although i have Pfsense with a WG VPN to a standard linux install)

I setup a port forward on my pfsense wan interface to the wg ip of the linux box which is connected to a tunnel on pfsense.
It did not work until i changed the allowed IPs of the linux box to 0.0.0.0/0 as of course allowed IPs is kind of a acl at this point.

Can you confirm the allowed IP for the site A peer on the Site B allows 0.0.0.0/0?

**Comment by kevindd992002** [comment]
> 
> 
> @kevindd992002 Ive just tried to test out your issue from your first post. (although i have Pfsense with a WG VPN to a standard linux install)
> 
> I setup a port forward on my pfsense wan interface to the wg ip of the linux box which is connected to a tunnel on pfsense.
> It did not work until i changed the allowed IPs of the linux box to 0.0.0.0/0 as of course allowed IPs is kind of a acl at this point.
> 
> Can you confirm the allowed IP for the site A peer on the Site B allows 0.0.0.0/0?
> 
> Until i added 0.0.0.0/0 I couldnt not see the packets arriving on site B wg interface with tcpdump

Thanks for looking at this. As for your question, yes, I already have 0.0.0.0/0 in the allowed IPs for the site A peer on site B because that was what solved issue #2 in my first post as I explained in one of my posts above:

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/issues/90#issuecomment-851910541

I understand what you're saying. In issue #2, the 0.0.0.0/0 allowed IP acted as an ACL for outbound traffic (initiated from site B, through the tunnel, and out to site A's WAN interface). Since the destination IP for this traffic is from the Internet, then 0.0.0.0/0 was needed. It's exactly the same concept for what could have been the solution for #1 as you explained but my case is slightly different than what you're experiencing.

1) In your case, you do not see the packets arriving on Site B's WG interface.
2) In my case, I do see the packets arriving on Site B's WG interface. I even see that the return traffic. The problem is that the return traffic goes through Site B's WAN interface because it is following the default route in its routing table. This is proof that reply-to's are not working. If they were working, Site B's will send the traffic (destination IP=Internet) back out the WG interface because it knows that the forward traffic came from that interface.

I hope that makes sense.

**Comment by Tigger2014** [comment]
ah thanks for the clarification, I will likely need to test this with another pfsense fw so i have one at each end. to see how the reply-to's are behaving on that setup. Hopefully we can produce a way to recreate the issue on a pure freeBSD install if the issue is within wireguard as that would be something Jason wanted to look at.

**Comment by kevindd992002** [comment]
> 
> 
> ah thanks for the clarification, I will likely need to test this with another pfsense fw so i have one at each end. to see how the reply-to's are behaving on that setup. Hopefully we can produce a way to recreate the issue on a pure freeBSD install if the issue is within wireguard as that would be something Jason wanted to look at.

Got it. Let me know if you need any kind of help/testing from my side.

**Comment by Tigger2014** [comment]
Hi @kevindd992002 ,

completed some more testing, on Site B have you set the upstream gateway on the WG interface? If not reply-to is not added to the pf rules.

The upstream gateway should be set to the gw on the other end at Site A

**Comment by kevindd992002** [comment]
> 
> 
> Hi @kevindd992002 ,
> 
> completed some more testing, on Site B have you set the upstream gateway on the WG interface? If not reply-to is not added to the pf rules.
> 
> The upstream gateway should be set to the gw on the other end at Site A

Aha! That I did not do. So at both sites, I should set the WG interface's upstream gateway to the WG interface IP of the other end, correct? Is there any caveats in doing this?

**Comment by kevindd992002** [comment]
IT WORKED :) As soon as I set the upstream gateway of the WG interface in Site B to Site A's WG interface IP, it started working. Now I'm wondering if it's best to do the same thing on Site A's WG interface.

**Comment by Tigger2014** [comment]
I dont believe it would cause any harm as long as its not set as the default gateway on the system. It essentially lets. pfsense know more than the subnet assigned to that interface is reachable there so applies the reply-to in pf.

Glad we got it sorted

**Comment by kevindd992002** [comment]
@Tigger2014 Just finished a more in-depth testing. Although it fixed the reply-to issue, as soon as I assign an upstream gateway to either site, it broke my PBR's. From Site B, here are some sample PBR's:

![image](https://user-images.githubusercontent.com/3907957/125839124-f9ab6cbd-2736-45f7-bd71-f42f368f6602.png)

They just won't work. It's as if traffic is blocked from going out the tunnel.

**Comment by Tigger2014** [comment]
Is the Failover gateway the same as the upstream on the Wg interface?

**Comment by kevindd992002** [comment]
Yes. The failover has the upstream on the WG interface as Tier 1 so it uses that.

**Comment by kevindd992002** [comment]
Ahh, I think I know why. When you assign an upstream gateway to an interface, pfsense automatically creates outbound NAT rules for it. This includes outbound NATTing Site B's subnets to the WG interface IP when the packets pass through it. On Site A, I don't have an outbound NAT rule for packets with source IP=Site B WG interface IP because I'm trying to avoid translation on both sides altogether.

In a normal pfsense S2S WG setup, is the upstream gateway set? If so, do you just let it create those automatic outbound NAT rules and have pfsense SNAT? This makes sense for a WAN interface but not for a WG interface.

**Comment by Tigger2014** [comment]
Charge the nat mode and manually do nat is likely the best option here

**Comment by kevindd992002** [comment]
Ok, got it. I'll go ahead this case now because at this point this is not a WG issue but is something that's expected of pfsense when you configure interfaces. The solution is one of the two options:

1. No upstream gateway, no reply-to, use hybrid outbound NAT mode to add a couple of outbound NAT rules for the use case.
2. Assign an upstream gateway, reply-to works, but manual outbound NAT mode is required to fully control the rules.

I'll probably try #2 since to avoid any unnecessary translations.

**Comment by tcquade** [comment]
You will probably want to use NAT Hybrid Outbound rather than Manual Outbound as pfsense sets up auto outbound rules for things such as openvpn and ipsec (there may be others).

 

Ted

**Comment by Tigger2014** [comment]
Ah yes, Use hybrid and add a rule with No Nat ticked to cover that interface.
![image](https://user-images.githubusercontent.com/2319079/125844418-a3205834-43b6-4a5a-bce5-6ff472f3437b.png)

**Comment by kevindd992002** [comment]
Right, I did a quick test and manual outbound NAT is too much work and could break things easily. If it helps though, when I was using OpenVPN with pfsense, reply-to's were working just fine even though you can't really do manual configuration (including adding an upstream gateway) in the interface settings.

**Comment by Tigger2014** [comment]
@kevindd992002 see my reply above, Regarding OVPN it does a lot underneath to integrate. WG but the nature of being a pkg is a little less tightly coupled to the system and also designed more to just present an interface and allow pfsense to do the rest.

My reply above about using Hybrid nat with a manual no rule is likely the easiest approach

**Comment by kevindd992002** [comment]
@Tigger2014 Yes, I just tried it and it works perfectly. I now have a WG S2S environment without the unnecessary NAT's and reply-to's working.

**Comment by Tigger2014** [comment]
@kevindd992002 Fantastic, I believe this issue is fully resolved now, Including the issue being with pfsense?

**Comment by kevindd992002** [comment]
> 
> 
> @kevindd992002 Fantastic, I believe this issue is fully resolved now, Including the issue being with pfsense?

Exactly. I knew it was just a misconfiguration somewhere when using WG and it turned out it was. Thanks for your time and effort again.
