### ISSUE TITLE
WF site-to-site speed issue

### ISSUE THREAD

**Issue by kevindd992002** [theonemcdonald/pfSense-pkg-WireGuard#93]
**Describe the bug**
I know you said in one of your videos that it "seems" that the MTU/MSS issue with WG has been fixed and there's no need to modify it to 1420. I see in the Status tab that it is indeed set to 1500. However, when you assign the WG tunnel to an interface, do I still need to set it to MTU and MSS to 1420?

I'm trying to test the tunnel transfer speed between the two sites (200Mbps link in between) but I'm getting all sorts of bandwidth issues. It starts at 80Mbps and drops down erratically to less than 10Mbps. Copying a large file from the remote site has also very inconsistent speeds. With WG in 2.5.0, I did get consistent and full speeds when I do the same test. Not sure if this has to do something with the MTU/MSS issue.

EDIT: I created another tunnel but this time for remote access (road warrior).  I connected to that tunnel from a Windows machine in a remote network. This speed issue was non-existent and it was able to saturate the full bandwidth so I know that my pfsense hardware is not a choke point. The pfsense hardware used for both sites are 100% identical so not sure what's going on here.

**Version information (please complete the following information):**

    PfSense: 2.5.1
    WireGuard-tools: 1.0.20210424
    WireGuard-kmod: 0.0.20210503
    pfSense-pkg-WireGuard: 0.1.2

**Comment by theonemcdonald** [comment]
WireGuard by design can pass arbitrary MTUs in the tunnel, ensuring that the packets are defragmented before handing off to the host network stack. However, there will always be fragmentation outside the tunnel when using an MTU >1420. This does add overhead because WireGuard has to defragment the packets on both ends. I can't imagine the drastic speed differences you are seeing would be caused by MTU fragmentation alone. I will do more testing here though

**Comment by kevindd992002** [comment]
Yeah, I also don't think it's fragmentation causing the issue. When I try to transfer a file between the two sites, you can see how it's having a hard time reaching even just 10Mbps. The Windows transfer speed even shows as low as in the Kbps range. It's as if something is being throttled along the way.

**Comment by theonemcdonald** [comment]
Can you iperf across it?

**Comment by kevindd992002** [comment]
Yes, that was the first speedtest I did. 

With MTU/MSS blank on the WG interface:
```

iperf 3.9
FreeBSD pfSense.home.arpa 12.2-STABLE FreeBSD 12.2-STABLE 1b709158e581(RELENG_2_5_0) pfSense amd64
Control connection MSS 1460
Time: Wed, 02 Jun 2021 15:22:20 UTC
Connecting to host 10.0.3.2, port 5201
      Cookie: cvuxollirnigijm6j3amwzzgtky4yslezlp6
      TCP MSS: 1460 (default)
[  5] local 10.0.3.1 port 21385 connected to 10.0.3.2 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  7.89 MBytes  66.2 Mbits/sec   12   43.9 KBytes       
[  5]   1.00-2.01   sec  3.50 MBytes  29.2 Mbits/sec    3   1.41 KBytes       
[  5]   2.01-3.00   sec  0.00 Bytes  0.00 bits/sec    3   1.41 KBytes       
[  5]   3.00-4.02   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  5]   4.02-5.01   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  5]   5.01-6.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  5]   6.00-7.00   sec   679 KBytes  5.59 Mbits/sec   59   41.3 KBytes       
[  5]   7.00-8.00   sec  10.7 MBytes  89.3 Mbits/sec    0   96.9 KBytes       
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    3   1.41 KBytes       
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    2   1.41 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  22.7 MBytes  19.1 Mbits/sec   84             sender
[  5]   0.00-10.29  sec  22.6 MBytes  18.4 Mbits/sec                  receiver
CPU Utilization: local/sender 14.4% (2.2%u/12.3%s), remote/receiver 4.8% (0.5%u/4.3%s)
snd_tcp_congestion newreno
rcv_tcp_congestion newreno

iperf Done.
```

When I change the MSS to 1420 on the WG interfaces on both sides, it does seem to produce expected speeds, BUT does not fix real world tests like file transfer speeds.

```
iperf 3.9
FreeBSD pfSense.home.arpa 12.2-STABLE FreeBSD 12.2-STABLE 1b709158e581(RELENG_2_5_0) pfSense amd64
Control connection MSS 1380
Time: Wed, 02 Jun 2021 15:26:10 UTC
Connecting to host 10.0.3.2, port 5201
      Cookie: ps5zp247avcjyjfjjwfhbzaul5mjknuuekqw
      TCP MSS: 1380 (default)
[  5] local 10.0.3.1 port 43216 connected to 10.0.3.2 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  8.89 MBytes  74.6 Mbits/sec   49   50.9 KBytes       
[  5]   1.00-2.00   sec  8.11 MBytes  68.1 Mbits/sec   60   25.5 KBytes       
[  5]   2.00-3.00   sec  9.85 MBytes  82.6 Mbits/sec   46   52.2 KBytes       
[  5]   3.00-4.00   sec  8.86 MBytes  74.4 Mbits/sec   39   64.6 KBytes       
[  5]   4.00-5.00   sec  11.0 MBytes  92.0 Mbits/sec   68   54.9 KBytes       
[  5]   5.00-6.00   sec  8.85 MBytes  74.2 Mbits/sec   69   43.0 KBytes       
[  5]   6.00-7.00   sec  9.11 MBytes  76.4 Mbits/sec   58   48.1 KBytes       
[  5]   7.00-8.00   sec  6.43 MBytes  53.9 Mbits/sec   66   34.9 KBytes       
[  5]   8.00-9.00   sec  12.8 MBytes   108 Mbits/sec   66   26.8 KBytes       
[  5]   9.00-10.00  sec  9.09 MBytes  76.1 Mbits/sec   54   88.8 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  93.0 MBytes  78.0 Mbits/sec  575             sender
[  5]   0.00-10.10  sec  93.0 MBytes  77.2 Mbits/sec                  receiver
CPU Utilization: local/sender 32.2% (3.4%u/28.7%s), remote/receiver 14.3% (1.5%u/12.8%s)
snd_tcp_congestion newreno
rcv_tcp_congestion newreno

iperf Done.
```

The link between the two sites is 200Mbps during the day only. It lowers down to 100Mbps during the night. That's why you see a seemingly 100Mbps cap on the 2nd iperf test.

**Comment by kevindd992002** [comment]
Here's a file transfer traffic graph:

![image](https://user-images.githubusercontent.com/3907957/120508697-84ab6f00-c3fa-11eb-9f6e-e81614f5c9e4.png)

It doesn't even want to start the transfer.

**Comment by theonemcdonald** [comment]
Interesting, I might be totally off with my assertion concerning overhead and fragmentation. Because I don’t touch anything in the kernel , it’s hard to say where the problem is. I have site to site links between two pfSense boxes that I can saturate without issue, though I haven’t specifically tested SMB transfers

**Comment by kevindd992002** [comment]
When you try and saturate these links with iperf while keeping the MTU/MSS WG interface fields blank, do you get the same result as I do?

**Comment by kevindd992002** [comment]
It looks like changing both MTU and MSS to 1420 fixed my issue:

![image](https://user-images.githubusercontent.com/3907957/120521257-541e0200-c407-11eb-9d24-21ba70557931.png)

So yeah, something to look out for with a WG tunnel. I'm not entirely sure what disadvantages I'm getting with lowering those values though.

**Comment by theonemcdonald** [comment]
Thanks for the feedback! This looks like something we need to look into, and likely address with the kernel development efforts as this project doesn't touch kernel or otherwise compiled source

**Comment by theonemcdonald** [comment]
https://lists.zx2c4.com/pipermail/wireguard/2021-June/006780.html

**Comment by Tigger2014** [comment]
The links between each site on the WAN side are they full 1500 MTU?

**Comment by kevindd992002** [comment]
> The links between each site on the WAN side are they full 1500 MTU?

Yes, they're both set to their blank defaults, so 1500.
