### ISSUE TITLE
[BUG] Tunnel/interface IP address configured incorrectly

### ISSUE THREAD

**Issue by Zepmann** [theonemcdonald/pfSense-pkg-WireGuard#95]
**Describe the bug**

**To Reproduce**
Install the package. Add a new Wireguard VPN Tunnel. Use the 'Add Address' function to add an inner-tunnel address for pfSense:

![image](https://user-images.githubusercontent.com/4273943/120481793-c31c3c00-c3b0-11eb-8222-33561dea2889.png)

Apply changes.

Now assign an interface to the 'tun_wg0 (tun_wg0)' port. That is quite redundant/meaningless, but I digress...

Edit the interface. This is the result:
![image](https://user-images.githubusercontent.com/4273943/120482066-0c6c8b80-c3b1-11eb-9788-783a68468fa5.png)

And this is the result on the dashboard when the interface is enabled and IPv4 Configuration Type is left on 'None':
![image](https://user-images.githubusercontent.com/4273943/120482253-39b93980-c3b1-11eb-81e8-e038f2529263.png)

**Expected behavior**
[This is what the interface page should tell the user](https://forum.netgate.com/assets/uploads/files/1614030878719-interface.png) (taken from [here](https://forum.netgate.com/topic/160378/wg-not-routing-or-sending-traffic/13)).

Furthemore, the IP address(es) as configured for the WireGuard Tunnel should be used to configure the interface.

**Screenshots**
See the screenshots in the description above.

**Version information (please complete the following information):**
 - PfSense: 2.51
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.2

**Additional context**
This bug report might be part of a series of bugs that I have when trying to create a WireGuard client configuration. Another bug I have is that no automatic gateway is created, which is quite frustrating since it is needed for effective routing and NAT'ing.

**Comment by theonemcdonald** [comment]
This is not a bug. Once you assign the interface in pfSense, you don't configure the address via the WireGuard UI.

**Comment by Zepmann** [comment]
This is quite confusing. Maybe it might be a good idea to add a caveat to the documentation about this, so that the user does not enter the IP address(es) twice, which is unnecessary.

**Comment by theonemcdonald** [comment]
Updating the documentation is an on-going project (we are welcome to contributions here too!). This is something I mentioned a while back in one of my project report videos (https://youtu.be/ljcJE7bZNWE?t=468). This video is quite old now, but it explains the flow.

**Comment by theonemcdonald** [comment]
![image](https://user-images.githubusercontent.com/3102039/120486725-4fb00580-c383-11eb-9deb-a0529777bc16.png)
