### ISSUE TITLE
[BUG] Missing automatic dynamic gateway

### ISSUE THREAD

**Issue by Zepmann** [theonemcdonald/pfSense-pkg-WireGuard#96]
**Describe the bug**
A gateway is not created when an interface is assigned. [The WireGuard documentation](https://docs.netgate.com/pfsense/en/latest/vpn/wireguard/assign.html) (to which this document refers) states:

```
Some functionality for WireGuard interfaces depends upon them being assigned as their own interfaces on the firewall. Benefits of assignment include:
- Adds a firewall tab under Firewall > Rules
- Allows the interface to be selected for use with NAT rules
- Allows the interface to be selected throughout the GUI and packages for various purposes
- ** Adds an automatic dynamic gateway for use with routing, policy routing, gateway groups, etc. **
- Rules on assigned interface tabs get reply-to which ensures return routing will exit back the expected interface for inbound connections.
```

I do not see this behavior. Neither do I know which IP address to use for the gateway if I would add it manually. I configured everything as [noted and shown here[https://forum.netgate.com/post/967147]. WireGuard Status shows the tunnel is 'up', but I am unable to make any kind of connection through the network segment I assigned as to be routed out through WireGuard.

**To Reproduce**
Install the package. Add a new WireGuard VPN Tunnel. Assign an interface. See the routing page. No gateway was created.

**Expected behavior**
An 'automatic dynamic gateway' should be visible after creating a WireGuard VPN Tunnel and assigning an interface..

**Screenshots**
See what I reference above. My configuration is exactly the same, with the only exception is that I am trying to route all traffic from an entire network through WireGuard.

**Version information (please complete the following information):**
 - PfSense: 2.51
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.2

**Additional context**
If there will be no automatic dynamic gateway, it might be a good idea to remove the link to official pfSense documentation, since it is not representative of the functionality of this package.

Ask away if more information is desired.

**Comment by theonemcdonald** [comment]
Again, this is a change from the 2.5.0 implementation that we can't work around (documentation needs updating for sure). You will have to create your own gateway entries just as if you were configuring a routed or WAN link

**Comment by Zepmann** [comment]
Could you please also look at this?

> I configured everything as [noted and shown here](https://forum.netgate.com/post/967147). WireGuard Status shows the tunnel is 'up', but I am unable to make any kind of connection through the network segment I assigned as to be routed out through WireGuard.

Note that I created a dynamic gateway. Is this the correct procedure?

**Comment by theonemcdonald** [comment]
I would recommend only loosely considering and following old documentation.

It sort of depends on what you're trying to do. If you are setting up a privacy VPN like Mullvad, or another service where they give you a configuration file with /32 and /128, you will want to set both your interface address and your gateway addresses to the same thing...yeah, confusing but that is WireGuard. 

If you're setting up a site-to-site VPN and your tunnel networks are larger than a /32, you could create your gateway IP set to the remote side of the link. That would make gateway monitor useful for measuring latency and failover etc.

**Comment by Zepmann** [comment]
My situation is a 'privacy VPN' (although the reason is not privacy). It is indeed Mullvad I am trying to connect to.

I am currently not in a position to try it right now, but will do so later and report back. Thanks for your feedback!

**Comment by theonemcdonald** [comment]
Mullvad is one that I test against, so your success rate should be quite high ;)

**Comment by Zepmann** [comment]
My last problem was with a rogue router in my network. I can neither confirm nor deny that this was my own doing.

What I can confirm are the required settings for a public ('outgoing' or 'privacy') VPN. Note that these steps are not the most efficient way to configure everything, but they are most consistent. You can add this to the documentation/wiki.

1. Create a new WireGuard tunnel. Use the private key your VPN provider provides, or generate your own and upload the public key to your VPN provider (whichever method is supported). Use the default value for 'Listen Port'. Do not use the 'Add Address' function. Save.
2. Add a peer. Assign the tunnel which was created in the previous step. Disable the 'Dynamic Endpoint' option, and enter the endpoint and port number provided by your VPN provider to connect to. Leave Keep Alive empty if your pfSense instance is directly connected to the internet. Otherwise, a value of 20 seconds can be used to keep the connection open in most circumstances where pfSense outgoing traffic passes another router/firewall before entering the internet. Add the public key of the VPN provider, and a pre-shared key if the provider requires it. Finally, enter the allowed IPs provided by the VPN provider. (which are most likely 0.0.0.0/0 for IPv4, and ::/0 for IPv6). Save.
3. Apply the new settings, and go to the WireGuard Status page. Confirm that the tunnel is up. Double check the previously entered data if the interface is down.
4. Go to Interfaces -> Assignments, and add a new interface based on the new 'tun_wg' port.  Open the interface configuration. Enable the interface and change its name to something recognizable. Set IPv4/IPv6 Configuration type to Static IPv4/IPv6 (depending on which IP versions your VPN provider supports and which you want to use). Enter the 'tunnel' or 'interface' IP address(es) provided by your VPN provider in the relevant field(s). Save and Apply.
5. Go to System -> Routing. Add a new gateway which uses the interface that was created in the previous step. Give it a recognizable name. Configure the gateway with the IP address that was assigned to the interface in the previous step. Repeat this step if both IPv4 and IPv6 need to be configured. Save and Apply.
6. Go to Firewall -> NAT -> Outbound. Check which Outbound NAT Mode is configured. If it is Manual or Disabled, go to step 8. If it is Automatic (default) or Hybrid, go to step 7.
7. Go to Interfaces -> Assignments. Edit the configuration of the VPN interface. Configure 'IPv4/IPv6 Upstream gateway' with the gateway(s) configured in step 5. Save and apply.
8. Go to Firewall -> Rules. Choose a local (LAN) network that will use the VPN connection. Add a new rule to the top of the rules (for testing, it can be moved later). This is where outgoing traffic over the VPN interface can be filtered A good starting point for testing is to simply allow all outgoing traffic. Set 'Protocol' to 'Any'. Leave 'Source' and 'Destination' as they are. Open the Advanced Options, and set 'Gateway' to the gateway that was created in the previous step. Repeat this step if both IPv4 and IPv6 need to be configured. Save and Apply.
9. If in step 6 it was determined that Outbound NAT Mode is Automatic or Hybrid, skip this step. Otherwise, go to Firewall -> NAT -> Outbound. If outbound NAT Mode is disabled, put it in manual mode. Add a new mapping. Use the interface of the VPN and the relevant address family/ies. Set the source to the IP subnet of the local network of which the outgoing traffic must go through the VPN. Leave all other settings default. Save and Apply.

Now test within the relevant network whether an internet connection is available. You can for example use [WhatIsMyIP.com](https://www.whatismyip.com/) to see which outgoing IP address you are using. If correctly configured, this should be an IP address of your VPN provider.

Now the fun part begins. You can fine tune the firewall rule(s) created in step 8 to only allow specific traffic through the VPN. Together with other rules, this will allow you to configure which outgoing interface will be used for which traffic. If the rule in step 8 is the only rule, 6 and 7.all outgoing traffic of the relevant network will only use the VPN interface.

To configure multiple networks to use the same VPN connection, repeat steps 8 and 9 (if needed).

@theonemcdonald Thanks for your support!

**Comment by parker-stephens** [comment]
> My last problem was with a rogue router in my network. I can neither confirm nor deny that this was my own doing.
> 
> What I can confirm are the required settings for a public ('outgoing' or 'privacy') VPN. Note that these steps are not the most efficient way to configure everything, but they are most consistent. You can add this to the documentation/wiki.
> 
> 1. Create a new WireGuard tunnel. Use the private key your VPN provider provides, or generate your own and upload the public key to your VPN provider (whichever method is supported). Use the default value for 'Listen Port'. Do not use the 'Add Address' function. Save.
> 2. Add a peer. Assign the tunnel which was created in the previous step. Disable the 'Dynamic Endpoint' option, and enter the endpoint and port number provided by your VPN provider to connect to. Leave Keep Alive empty if your pfSense instance is directly connected to the internet. Otherwise, a value of 20 seconds can be used to keep the connection open in most circumstances where pfSense outgoing traffic passes another router/firewall before entering the internet. Add the public key of the VPN provider, and a pre-shared key if the provider requires it. Finally, enter the allowed IPs provided by the VPN provider. (which are most likely 0.0.0.0/0 for IPv4, and ::/0 for IPv6). Save.
> 3. Apply the new settings, and go to the WireGuard Status page. Confirm that the tunnel is up. Double check the previously entered data if the interface is down.
> 4. Go to Interfaces -> Assignments, and add a new interface based on the new 'tun_wg' port.  Open the interface configuration. Enable the interface and change its name to something recognizable. Set IPv4/IPv6 Configuration type to Static IPv4/IPv6 (depending on which IP versions your VPN provider supports and which you want to use). Enter the 'tunnel' or 'interface' IP address(es) provided by your VPN provider in the relevant field(s). Enable 'Block private networks and loopback addresses' and 'Block bogon networks'. This is a WAN interface, after all. In testing, I found out that these options do not block WireGuard connections, even if the provided IP address(es) is/are in private networks. Save and Apply.
> 5. Go to System -> Routing. Add a new gateway which uses the interface that was created in the previous step. Give it a recognizable name. Configure the gateway with the IP address that was assigned to the interface in the previous step. Repeat this step if both IPv4 and IPv6 need to be configured. Save and Apply.
> 6. Go to Firewall -> NAT -> Outbound. Check which Outbound NAT Mode is configured. If it is Manual or Disabled, go to step 8. If it is Automatic (default) or Hybrid, go to step 7.
> 7. Go to Interfaces -> Assignments. Edit the configuration of the VPN interface. Configure 'IPv4/IPv6 Upstream gateway' with the gateway(s) configured in step 5. Save and apply.
> 8. Go to Firewall -> Rules. Choose a local (LAN) network that will use the VPN connection. Add a new rule to the top of the rules (for testing, it can be moved later). This is where outgoing traffic over the VPN interface can be filtered A good starting point for testing is to simply allow all outgoing traffic. Set 'Protocol' to 'Any'. Leave 'Source' and 'Destination' as they are. Open the Advanced Options, and set 'Gateway' to the gateway that was created in the previous step. Repeat this step if both IPv4 and IPv6 need to be configured. Save and Apply.
> 9. If you use IPv4 and if in step 6 it was determined that Outbound NAT Mode is Automatic or Hybrid, skip this step. Go to Firewall -> NAT -> Outbound. If Outbound NAT Mode is disabled, change it to manual mode. Add a new mapping. Use the interface of the VPN and explicitly choose IPv4. Set the source to the IPv4 subnet of the local network of which the outgoing traffic must go through the VPN. Leave all other settings default. Save and Apply.
> 10. If you use IPv6, go to Firewall -> NAT -> Outbound. If Outbound NAT mode is automatic, change it to hybrid mode. Add a new mapping. Use the interface of the VPN and explicitly choose IPv6. Set the source to the IPv6 subnet of the local network of which the outgoing traffic must go through the VPN. Leave all other settings default. Save and Apply.
> 
> Now test within the relevant network whether an internet connection is available. You can for example use [WhatIsMyIP.com](https://www.whatismyip.com/) to see which outgoing IP address you are using. If correctly configured, this should be an IP address of your VPN provider.
> 
> Now the fun part begins. You can fine tune the firewall rule(s) created in step 8 to only allow specific traffic through the VPN. Together with other rules, this will allow you to configure which outgoing interface will be used for which traffic. If the rule in step 8 is the only rule, all outgoing traffic of the relevant network will only use the VPN interface.
> 
> To configure multiple networks to use the same VPN connection, repeat steps 8-10.
> 
> @theonemcdonald Thanks for your support!

You are awesome!!! I could not figure out how to set this up for the life of me, but following your instructions worked great and was super easy!
