### ISSUE TITLE
Warning: htmlspecialchars() expects parameter 1 to be string, array given in /usr/local/pkg/wireguard/wg.inc on line 828 0.0.0.0/0

### ISSUE THREAD

**Issue by infosecmatters2021** [theonemcdonald/pfSense-pkg-WireGuard#99]
This message appeared after I created a new peer with allowed IPs 0.0.0.0/0. Tried to change allowed IPs on another install with existing tunnel and peer. It showed the same error (different line as it was pfSense-pkg-WireGuard-1.2 (no further commits)).

pfSense version - 2.6.0.a.20210603.0100 (latest)
pfSense-pkg-WireGuard-1.2 (including recent commits)

**Comment by infosecmatters2021** [comment]
Updated wg_guiconfig.inc

Original error message resolved. New error appears:
Warning: array_map(): Expected parameter 2 to be an array, null given in /usr/local/pkg/wireguard/wg_guiconfig.inc on line 422 (none)

**Comment by theonemcdonald** [comment]
Bleh, sorry about that. Try again

Thanks

**Comment by infosecmatters2021** [comment]
Thank you!
